import { $eq, CodePosition, CodeRange } from "../runtime-exports";
export class CodeDocument {
    constructor(lines: string[], props?: any) { this._lines = lines; if (props && typeof props === 'object') Object.assign(this, props); }
    _lines: string[];
    static _empty: CodeDocument | undefined;
    static get empty(): CodeDocument { return CodeDocument._empty ??= new CodeDocument(['']); }
    get lines(): string[] { return this._lines; }
    get lineCount(): number { return this._lines.length; }
    get text(): string { return this._lines.join('\n'); }
    get length(): number { let total = 0;for (let i = 0; i < this._lines.length; i++) total += this._lines[i].length + 1;return total - 1; }
    get end(): CodePosition { return new CodePosition(this._lines.length - 1, this._lines[this._lines.length - 1].length); }
    static fromText(text: string) { let lines: string[] = [];let current = $eq.text.stringBuilder();for (let i = 0; i < text.length; i++) {let c = text[i];if (c === '\r') {if (i + 1 < text.length && text[i + 1] === '\n') i++;lines.push(current.toString());current.clear();continue;}if (c === '\n') {lines.push(current.toString());current.clear();continue;}current.append(c);}lines.push(current.toString());return new CodeDocument(lines); }
    line(index: number) { return index >= 0 && index < this._lines.length ? this._lines[index] : ''; }
    clamp(position: CodePosition) { let line = Math.min(Math.max(position.line, 0), this._lines.length - 1);let column = Math.min(Math.max(position.column, 0), this._lines[line].length);return new CodePosition(line, column); }
    offsetOf(position: CodePosition) { let clamped = this.clamp(position);let offset = 0;for (let i = 0; i < clamped.line; i++) offset += this._lines[i].length + 1;return offset + clamped.column; }
    positionOf(offset: number) { if (offset <= 0) return CodePosition.start;let remaining = offset;for (let line = 0; line < this._lines.length; line++) {let length = this._lines[line].length;if (remaining <= length) return new CodePosition(line, remaining);remaining -= length + 1;}return this.end; }
    textIn(range: CodeRange) { let start = this.clamp(range.start);let end = this.clamp(range.end);if ($eq.equals(start, end)) return '';if (start.line === end.line) return this._lines[start.line].slice(start.column, end.column);let text = $eq.text.stringBuilder();text.append(this._lines[start.line].slice(start.column));for (let line = start.line + 1; line < end.line; line++) {text.append('\n');text.append(this._lines[line]);}text.append('\n');text.append(this._lines[end.line].slice(0, end.column));return text.toString(); }
    replace(range: CodeRange, text: string) { let caret; const $r = (() => { let start = this.clamp(range.start);let end = this.clamp(range.end);let inserted = CodeDocument.fromText(text);let lines: string[] = [];for (let i = 0; i < start.line; i++) lines.push(this._lines[i]);let head = this._lines[start.line].slice(0, start.column);let tail = this._lines[end.line].slice(end.column);if (inserted.lineCount === 1) {lines.push(head + inserted.line(0) + tail);caret = new CodePosition(start.line, start.column + inserted.line(0).length);} else {lines.push(head + inserted.line(0));for (let i = 1; i < inserted.lineCount - 1; i++) lines.push(inserted.line(i));let last = inserted.line(inserted.lineCount - 1);lines.push(last + tail);caret = new CodePosition(start.line + inserted.lineCount - 1, last.length);}for (let i = end.line + 1; i < this._lines.length; i++) lines.push(this._lines[i]);return new CodeDocument(lines); })(); return { $: $r, caret }; }
    previous(position: CodePosition) { let here = this.clamp(position);if (here.column > 0) return $eq.withPatch(here, { column: here.column - 1 });if (here.line === 0) return CodePosition.start;return new CodePosition(here.line - 1, this._lines[here.line - 1].length); }
    next(position: CodePosition) { let here = this.clamp(position);if (here.column < this._lines[here.line].length) return $eq.withPatch(here, { column: here.column + 1 });if (here.line === this._lines.length - 1) return here;return new CodePosition(here.line + 1, 0); }
    lineStart(position: CodePosition) { let here = this.clamp(position);let line = this._lines[here.line];let indent = 0;while (indent < line.length && (line[indent] === ' ' || line[indent] === '\t')) indent++;return $eq.withPatch(here, { column: here.column === indent ? 0 : indent }); }
    lineEnd(position: CodePosition) { let here = this.clamp(position);return $eq.withPatch(here, { column: this._lines[here.line].length }); }
    wordAt(position: CodePosition) { let here = this.clamp(position);let line = this._lines[here.line];if (line.length === 0) return new CodeRange(here);let index = Math.min(here.column, line.length - 1);if (!CodeDocument.isWordChar(line[index])) {if (here.column > 0 && CodeDocument.isWordChar(line[here.column - 1])) index = here.column - 1; else {let symbolStart = index;while (symbolStart > 0 && !CodeDocument.isWordChar(line[symbolStart - 1]) && !(/^\s$/.test(line[symbolStart - 1]))) symbolStart--;let symbolEnd = index;while (symbolEnd < line.length && !CodeDocument.isWordChar(line[symbolEnd]) && !(/^\s$/.test(line[symbolEnd]))) symbolEnd++;return new CodeRange($eq.withPatch(here, { column: symbolStart }), $eq.withPatch(here, { column: symbolEnd }));}}let start = index;while (start > 0 && CodeDocument.isWordChar(line[start - 1])) start--;let end = index;while (end < line.length && CodeDocument.isWordChar(line[end])) end++;return new CodeRange($eq.withPatch(here, { column: start }), $eq.withPatch(here, { column: end })); }
    indentOf(line: number) { let text = this.line(line);let indent = 0;while (indent < text.length && (text[indent] === ' ' || text[indent] === '\t')) indent++;return text.slice(0, indent); }
    static isWordChar(c: string) { return (/^[\p{L}\p{Nd}]$/u.test(c)) || c === '_'; }
}

