import { MermaidEdge, MermaidEdgeRef, MermaidGraph, MermaidMessage, MermaidNode, MermaidNodeRef } from "../runtime-exports";
export class MermaidParser {
    static _skipWords: string[] | undefined;
    static get skipWords(): string[] { return MermaidParser._skipWords ??= ['subgraph', 'end', 'style', 'classDef', 'class', 'click', 'linkStyle', 'direction']; }
    static _messageArrows: string[] | undefined;
    static get messageArrows(): string[] { return MermaidParser._messageArrows ??= ['-->>', '->>', '-->', '->']; }
    static parse(source: string) { if (!source) return null;let lines = source.replaceAll('\r\n', '\n').split('\n');let graph = MermaidParser.headerOf(lines);if (graph == null) return null;for (let i = 0; i < lines.length; i++) {let line = MermaidParser.stripComment(lines[i]).trim();if (line.length === 0) continue;if (MermaidParser.isHeader(line)) continue;if (graph.kind === 'sequence') MermaidParser.parseSequenceLine(graph, line); else MermaidParser.parseFlowchartLine(graph, line);}if (graph.kind === 'sequence') return graph.messages.length === 0 && graph.nodes.length === 0 ? null : graph;return graph.nodes.length === 0 ? null : graph; }
    static headerOf(lines: string[]) { for (let i = 0; i < lines.length; i++) {let line = MermaidParser.stripComment(lines[i]).trim();if (line.length === 0) continue;if (line.startsWith('sequenceDiagram')) return new MermaidGraph({ kind: 'sequence' });let rest = '';if (line.startsWith('flowchart')) rest = line.slice(9).trim(); else if (line.startsWith('graph')) rest = line.slice(5).trim(); else return null;if (rest === 'TD' || rest === 'TB') return new MermaidGraph({ vertical: true });if (rest === 'LR') return new MermaidGraph({ vertical: false });return null;}return null; }
    static isHeader(line: string) { return line.startsWith('sequenceDiagram') || line.startsWith('flowchart') || line.startsWith('graph'); }
    static stripComment(line: string) { let at = line.indexOf('%%');return at < 0 ? line : line.slice(0, at); }
    static parseFlowchartLine(graph: MermaidGraph, line: string) { for (const skip of MermaidParser.skipWords) if (line === skip || line.startsWith(skip + ' ')) return;let text = line.endsWith(';') ? line.slice(0, (line.length - 1)) : line;let from = MermaidParser.nodeRefAt(text, 0);if (from == null) return;MermaidParser.declare(graph, from);let pos = from.end;let current = from.id;while (true) {pos = MermaidParser.skipSpaces(text, pos);if (pos >= text.length) break;let edge = MermaidParser.edgeRefAt(text, pos);if (edge == null) break;pos = MermaidParser.skipSpaces(text, edge.end);let to = MermaidParser.nodeRefAt(text, pos);if (to == null) break;MermaidParser.declare(graph, to);graph.edges.push(new MermaidEdge({ from: current, to: to.id, label: edge.label, arrow: edge.arrow }));current = to.id;pos = to.end;} }
    static declare(graph: MermaidGraph, nodeRef: MermaidNodeRef) { for (const known of graph.nodes) {if (known.id !== nodeRef.id) continue;if (nodeRef.shaped) {known.label = nodeRef.label;known.shape = nodeRef.shape;}return;}graph.nodes.push(new MermaidNode({ id: nodeRef.id, label: nodeRef.label.length === 0 ? nodeRef.id : nodeRef.label, shape: nodeRef.shape })); }
    static skipSpaces(text: string, pos: number) { while (pos < text.length && text[pos] === ' ') pos++;return pos; }
    static isIdChar(c: string) { return (/^\p{L}$/u.test(c)) || (/^\p{Nd}$/u.test(c)) || c === '_'; }
    static nodeRefAt(text: string, pos: number) { let start = MermaidParser.skipSpaces(text, pos);let end = start;while (end < text.length && MermaidParser.isIdChar(text[end])) end++;if (end === start) return null;let node = new MermaidNodeRef({ id: text.slice(start, end), end: end });if (end >= text.length) return node;let c = text[end];if (c === '[') return MermaidParser.closeShape(text, end + 1, ']', 'rect', node);if (c === '{') return MermaidParser.closeShape(text, end + 1, '}', 'diamond', node);if (c === '(') {if (end + 1 < text.length && text[end + 1] === '(') return MermaidParser.closeShape(text, end + 2, '))', 'circle', node);return MermaidParser.closeShape(text, end + 1, ')', 'rounded', node);}return node; }
    static closeShape(text: string, from: number, closer: string, shape: string, node: MermaidNodeRef) { let close = text.indexOf(closer, from);if (close < 0) return null;let label = text.slice(from, close).trim();if (label.startsWith('"') && label.endsWith('"') && label.length >= 2) label = label.slice(1, (label.length - 1));node.label = label;node.shape = shape;node.shaped = true;node.end = close + closer.length;return node; }
    static edgeRefAt(text: string, pos: number) { let i = pos;let body = 0;while (i < text.length && (text[i] === '-' || text[i] === '=' || text[i] === '.')) {body++;i++;}if (body < 2) return null;let arrow = i < text.length && text[i] === '>';if (arrow) i++;let edge = new MermaidEdgeRef({ arrow: arrow, end: i });let after = MermaidParser.skipSpaces(text, i);if (after < text.length && text[after] === '|') {let close = text.indexOf('|', after + 1);if (close > after) {edge.label = text.slice((after + 1), close).trim();edge.end = close + 1;}}return edge; }
    static parseSequenceLine(graph: MermaidGraph, line: string) { if (line.startsWith('participant ') || line.startsWith('actor ')) {let rest = line.slice((line.indexOf(' ') + 1)).trim();let alias = rest;let display = rest;let asAt = rest.indexOf(' as ');if (asAt > 0) {alias = rest.slice(0, asAt).trim();display = rest.slice((asAt + 4)).trim();}MermaidParser.declareParticipant(graph, alias, display);return;}let colon = line.indexOf(':');if (colon <= 0) return;let head = line.slice(0, colon).trim();let label = line.slice((colon + 1)).trim();for (const arrow of MermaidParser.messageArrows) {let at = head.indexOf(arrow);if (at <= 0) continue;let from = head.slice(0, at).trim();let to = head.slice((at + arrow.length)).trim();if (from.length === 0 || to.length === 0) return;MermaidParser.declareParticipant(graph, from, from);MermaidParser.declareParticipant(graph, to, to);graph.messages.push(new MermaidMessage({ from: from, to: to, label: label, dashed: arrow.startsWith('--') }));return;} }
    static declareParticipant(graph: MermaidGraph, id: string, display: string) { for (const known of graph.nodes) if (known.id === id) return;graph.nodes.push(new MermaidNode({ id: id, label: display, shape: 'rect' })); }
}

