import { $eq, CodeDocument, CodeLanguageRules, CodeToken, CodeTokenKindValue } from "../runtime-exports";
export class PythonLanguage {
    constructor(props?: any) {  if (props && typeof props === 'object') Object.assign(this, props); }
    static normal: number = 0;
    static tripleDouble: number = 1;
    static tripleSingle: number = 2;
    static _keywords: Set<string> | undefined;
    static get keywords(): Set<string> { return PythonLanguage._keywords ??= new Set(['and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'match', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']); }
    static _builtins: Set<string> | undefined;
    static get builtins(): Set<string> { return PythonLanguage._builtins ??= new Set(['bool', 'bytes', 'dict', 'float', 'frozenset', 'int', 'list', 'object', 'set', 'str', 'tuple', 'type']); }
    static _constants: Set<string> | undefined;
    static get constants(): Set<string> { return PythonLanguage._constants ??= new Set(['True', 'False', 'None', 'self', 'cls']); }
    get name(): string { return 'Python'; }
    rules: CodeLanguageRules = new CodeLanguageRules('#', null, [['(', ')'], ['[', ']'], ['{', '}']], ['"', '\''], [':', '(', '[', '{'], [')', ']', '}'], 4);
    tokenize(line: string, state: number, into: CodeToken[]) { let i = 0;if (state !== PythonLanguage.normal) {let marker = state === PythonLanguage.tripleDouble ? '"""' : '\'\'\'';let close = line.indexOf(marker);if (close < 0) {PythonLanguage.add(into, 0, line.length, 'string');return state;}PythonLanguage.add(into, 0, close + 3, 'string');i = close + 3;}while (i < line.length) {let c = line[i];if ((/^\s$/.test(c))) {i++;continue;}if (c === '#') {PythonLanguage.add(into, i, line.length - i, 'comment');return PythonLanguage.normal;}if (PythonLanguage.tripleAt(line, i, '"') || PythonLanguage.tripleAt(line, i, '\'')) {let quote = line[i];let marker = quote === '"' ? '"""' : '\'\'\'';let close = line.indexOf(marker, i + 3);if (close < 0) {PythonLanguage.add(into, i, line.length - i, 'string');return quote === '"' ? PythonLanguage.tripleDouble : PythonLanguage.tripleSingle;}PythonLanguage.add(into, i, close + 3 - i, 'string');i = close + 3;continue;}if (c === '"' || c === '\'') {let start = i;if (i > 0 && 'fFrRbBuU'.indexOf(line[i - 1]) >= 0) start = i - 1;if (start < i && into.length > 0 && into[into.length - 1].end === i) into.splice(into.length - 1, 1);let end = PythonLanguage.scanQuoted(line, i + 1, c);PythonLanguage.add(into, start, (end < 0 ? line.length : end) - start, 'string');i = end < 0 ? line.length : end;continue;}if ((/^\p{Nd}$/u.test(c))) {let end = i;while (end < line.length && ((/^[\p{L}\p{Nd}]$/u.test(line[end])) || line[end] === '.' || line[end] === '_')) end++;PythonLanguage.add(into, i, end - i, 'number');i = end;continue;}if (c === '@') {let end = i + 1;while (end < line.length && (CodeDocument.isWordChar(line[end]) || line[end] === '.')) end++;PythonLanguage.add(into, i, end - i, 'attribute');i = end;continue;}if ((/^\p{L}$/u.test(c)) || c === '_') {let start = i;while (i < line.length && CodeDocument.isWordChar(line[i])) i++;let word = line.slice(start, i);let kind: CodeTokenKindValue = PythonLanguage.keywords.has(word) ? 'keyword' : PythonLanguage.constants.has(word) ? 'constant' : PythonLanguage.builtins.has(word) ? 'type' : PythonLanguage.nextNonSpace(line, i) === '(' ? 'function' : (/^\p{Lu}$/u.test(word[0])) ? 'type' : 'plain';PythonLanguage.add(into, start, i - start, kind);continue;}PythonLanguage.add(into, i, 1, '()[]{},:.'.indexOf(c) >= 0 ? 'punctuation' : 'operator');i++;}return PythonLanguage.normal; }
    static tripleAt(line: string, i: number, quote: string) { return i + 2 < line.length && line[i] === quote && line[i + 1] === quote && line[i + 2] === quote; }
    static scanQuoted(line: string, from: number, quote: string) { for (let i = from; i < line.length; i++) {if (line[i] === '\\') {i++;continue;}if (line[i] === quote) return i + 1;}return -1; }
    static nextNonSpace(line: string, from: number) { for (let i = from; i < line.length; i++) if (!(/^\s$/.test(line[i]))) return line[i];return '\0'; }
    static add(into: CodeToken[], start: number, length: number, kind: CodeTokenKindValue) { if (length <= 0) return;if (into.length > 0 && into[into.length - 1].kind === kind && into[into.length - 1].end === start) {into[into.length - 1] = $eq.withPatch(into[into.length - 1], { length: into[into.length - 1].length + length });return;}into.push(new CodeToken(start, length, kind)); }
}

