<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <IsPackable>true</IsPackable>
        <PackageId>eQuantic.UI.Material</PackageId>
        <Description>Material Design 3 integration for eQuantic.UI.</Description>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\eQuantic.UI.Server\eQuantic.UI.Server.csproj" />
        <ProjectReference Include="..\eQuantic.UI.Compiler\eQuantic.UI.Compiler.csproj" />
        <ProjectReference Include="..\eQuantic.UI.Components\eQuantic.UI.Components.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Build\eQuantic.UI.Material.targets" PackagePath="build" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Scripts\*.js" />
        <EmbeddedResource Include="Styles\**\*.css" />
    </ItemGroup>

</Project>