using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace eQuantic.UI.Generators;

/// <summary>
/// Turns a model's <c>DataAnnotations</c> into a <see cref="FormController"/> — at BUILD time,
/// because the alternative does not exist: DataAnnotations validates by REFLECTION, and reflection
/// is the one thing the transpiler cannot carry into a browser.
/// <para>
/// What it emits is ORDINARY calls to the same <c>Rules</c> a hand-written form uses. There is no
/// second validation engine here and that is the point: the generated form and the hand-written one
/// are the same object, so a model can adopt the bridge without the page changing, and a form can
/// outgrow it without a rewrite.
/// </para>
/// <para>
/// A field is a STRING, always — that is what a text box holds. A model's `int Age` becomes a field
/// whose rules parse it, not an int field, and the property types this understands are the ones a
/// text box can round-trip.
/// </para>
/// </summary>
[Generator]
public sealed class FormModelGenerator : IIncrementalGenerator
{
    private const string MarkerAttribute = "FormModelAttribute";

    internal static readonly DiagnosticDescriptor UnsupportedPropertyType = new(
        "EQ3103", "A form model property has a type no text box can hold",
        "'{0}.{1}' is a {2}, which this bridge does not carry — a form field is a string, and the "
        + "types it round-trips are text, numbers and bool. The property is skipped; add the field "
        + "by hand if the form needs it.",
        "eQuantic.UI", DiagnosticSeverity.Warning, isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor UnsupportedAttribute = new(
        "EQ3104", "A validation attribute has no rule to become",
        "[{0}] on '{1}.{2}' has no equivalent in Rules, so it is NOT enforced on this form. The "
        + "server still applies it — put the verdict back with ApplyServerErrors, or write the rule "
        + "by hand with Rules.Custom.",
        "eQuantic.UI", DiagnosticSeverity.Warning, isEnabledByDefault: true);

    internal static readonly DiagnosticDescriptor CompareTargetMissing = new(
        "EQ3105", "A [Compare] names a property this form does not have",
        "[Compare(\"{0}\")] on '{1}.{2}' names a property that is not a field of this form, so the "
        + "two values are never compared. Name a property of the same model.",
        "eQuantic.UI", DiagnosticSeverity.Warning, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var models = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, token) => Describe(ctx, token))
            .Where(static model => model is not null)
            .Collect();

        context.RegisterSourceOutput(models, static (spc, all) => Emit(spc, all));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<Model?> all)
    {
        var models = all.Where(m => m is not null).Select(m => m!)
            .GroupBy(m => m.FullName).Select(group => group.First())      // partials arrive twice
            .OrderBy(m => m.FullName, System.StringComparer.Ordinal)
            .ToList();
        if (models.Count == 0) return;

        foreach (var model in models)
        {
            foreach (var diagnostic in model.Diagnostics) spc.ReportDiagnostic(diagnostic);
            if (model.Fields.Count == 0) continue;

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine("using eQuantic.UI.Primitives;");
            source.AppendLine();
            source.AppendLine($"namespace {model.Namespace};");
            source.AppendLine();
            source.AppendLine($"/// <summary>The form <see cref=\"{model.Name}\"/> describes: one field");
            source.AppendLine("/// per property, and the rules its annotations asked for. Generated.</summary>");
            source.AppendLine($"public static class {model.FormName}");
            source.AppendLine("{");
            source.AppendLine("    /// <summary>An empty form with every rule the model declares.</summary>");
            source.AppendLine("    public static FormController Create()");
            source.AppendLine("    {");
            source.AppendLine("        var form = new FormController();");
            foreach (var field in model.Fields)
            {
                var rules = field.Rules.Count == 0 ? "" : $", [{string.Join(", ", field.Rules)}]";
                source.AppendLine($"        var {field.Local} = form.Add(\"{field.Name}\", \"\"{rules});");
            }
            // The cross-field rules go on AFTERWARDS, so a [Compare] never depends on the order the
            // properties happen to be declared in.
            foreach (var field in model.Fields)
                foreach (var comparison in field.CompareWith)
                    source.AppendLine($"        {field.Local}.AddRule(Rules.Matches({comparison}));");
            source.AppendLine("        return form;");
            source.AppendLine("    }");
            source.AppendLine("}");

            spc.AddSource($"{model.FormName}.g.cs", source.ToString());
        }
    }

    private static Model? Describe(GeneratorSyntaxContext ctx, System.Threading.CancellationToken token)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, token) is not INamedTypeSymbol symbol) return null;
        if (symbol.ContainingNamespace.IsGlobalNamespace) return null;

        var marker = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == MarkerAttribute);
        if (marker is null) return null;

        var named = marker.NamedArguments
            .FirstOrDefault(pair => pair.Key == "Name").Value.Value as string;
        var formName = string.IsNullOrWhiteSpace(named) ? symbol.Name + "Form" : named!;

        var diagnostics = new List<Diagnostic>();
        var fields = new List<Field>();
        var names = new HashSet<string>(System.StringComparer.Ordinal);

        // The model's own properties, in declaration order: a form reads top to bottom and so does
        // the page that draws it.
        foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (property.DeclaredAccessibility != Accessibility.Public) continue;
            if (property.IsStatic || property.IsIndexer || property.GetMethod is null) continue;

            var kind = TypeOf(property.Type);
            if (kind == ValueKind.Unsupported)
            {
                // Only complain about a property the model ANNOTATED: an unannotated navigation
                // property or a computed one is not somebody asking for a field.
                if (property.GetAttributes().Any(IsValidation))
                    diagnostics.Add(Diagnostic.Create(UnsupportedPropertyType,
                        property.Locations.FirstOrDefault(), symbol.Name, property.Name,
                        property.Type.ToDisplayString()));
                continue;
            }

            // `<name>Field`, not `_<name>`: an underscore reads as a FIELD in C#, and this is a
            // local. (The transpiler used to read it that way too, and emitted `this._password`
            // inside a static method.)
            var field = new Field(property.Name, Camel(property.Name) + "Field");
            foreach (var attribute in property.GetAttributes())
            {
                var name = attribute.AttributeClass?.Name;
                if (name is null || !IsValidation(attribute)) continue;
                var message = Message(attribute);
                switch (name)
                {
                    case "RequiredAttribute":
                        field.Rules.Add($"Rules.Required({message ?? ""})");
                        break;
                    case "EmailAddressAttribute":
                        field.Rules.Add($"Rules.Email({message ?? ""})");
                        break;
                    case "MinLengthAttribute":
                        field.Rules.Add($"Rules.MinLength({Int(attribute, 0)}{Comma(message)})");
                        break;
                    case "MaxLengthAttribute":
                        field.Rules.Add($"Rules.MaxLength({Int(attribute, 0)}{Comma(message)})");
                        break;
                    case "StringLengthAttribute":
                    {
                        var minimum = attribute.NamedArguments
                            .FirstOrDefault(pair => pair.Key == "MinimumLength").Value.Value as int?;
                        if (minimum is > 0) field.Rules.Add($"Rules.MinLength({minimum}{Comma(message)})");
                        field.Rules.Add($"Rules.MaxLength({Int(attribute, 0)}{Comma(message)})");
                        break;
                    }
                    case "RangeAttribute":
                        field.Rules.Add($"Rules.Range({Number(attribute, 0)}, {Number(attribute, 1)}{Comma(message)})");
                        break;
                    case "RegularExpressionAttribute":
                    {
                        var pattern = attribute.ConstructorArguments.FirstOrDefault().Value as string ?? "";
                        // Empty passes, like every rule but Required: an optional box left blank is
                        // absent, not badly formatted.
                        field.Rules.Add(
                            $"Rules.Custom({message ?? "\"Use the expected format.\""}, "
                            + $"value => value.Length == 0 || System.Text.RegularExpressions.Regex"
                            + $".IsMatch(value, \"{Escape(pattern)}\"))");
                        break;
                    }
                    case "CompareAttribute":
                    {
                        var other = attribute.ConstructorArguments.FirstOrDefault().Value as string ?? "";
                        field.CompareRequests.Add((other, property.Locations.FirstOrDefault()));
                        break;
                    }
                    default:
                        diagnostics.Add(Diagnostic.Create(UnsupportedAttribute,
                            property.Locations.FirstOrDefault(),
                            name.EndsWith("Attribute", System.StringComparison.Ordinal)
                                ? name.Substring(0, name.Length - "Attribute".Length)
                                : name,
                            symbol.Name, property.Name));
                        break;
                }
            }

            if (!names.Add(field.Name)) continue;
            fields.Add(field);
        }

        // [Compare] can only be resolved once every field is known — it names a property, and the
        // property may be declared after the one comparing to it.
        foreach (var field in fields)
        {
            foreach (var (other, location) in field.CompareRequests)
            {
                var target = fields.FirstOrDefault(f => f.Name == other);
                if (target is null || ReferenceEquals(target, field))
                {
                    diagnostics.Add(Diagnostic.Create(CompareTargetMissing, location,
                        other, symbol.Name, field.Name));
                    continue;
                }
                field.CompareWith.Add(target.Local);
            }
        }

        return new Model(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, formName,
            symbol.ToDisplayString(), fields, diagnostics);
    }

    /// <summary>An attribute from DataAnnotations — the namespace, not the name, so an app's own
    /// `[Required]` for something else is not mistaken for a rule.</summary>
    private static bool IsValidation(AttributeData attribute) =>
        attribute.AttributeClass?.ContainingNamespace?.ToDisplayString()
            == "System.ComponentModel.DataAnnotations";

    /// <summary>The message the annotation carries, as a C# literal, or null for the rule's own.</summary>
    private static string? Message(AttributeData attribute)
    {
        var text = attribute.NamedArguments
            .FirstOrDefault(pair => pair.Key == "ErrorMessage").Value.Value as string;
        return string.IsNullOrEmpty(text) ? null : $"\"{Escape(text!)}\"";
    }

    private static string Comma(string? message) => message is null ? "" : $", {message}";

    private static string Int(AttributeData attribute, int index) =>
        attribute.ConstructorArguments.Length > index
        && attribute.ConstructorArguments[index].Value is int value
            ? value.ToString(CultureInfo.InvariantCulture)
            : "0";

    /// <summary>A [Range] bound, which the attribute may carry as int, double or a STRING (its
    /// `(Type, string, string)` constructor) — all three become the double a rule takes.</summary>
    private static string Number(AttributeData attribute, int index)
    {
        var arguments = attribute.ConstructorArguments;
        // The (Type, string, string) overload puts the bounds at 1 and 2.
        var at = arguments.Length == 3 && arguments[0].Value is INamedTypeSymbol ? index + 1 : index;
        if (arguments.Length <= at) return "0";
        return arguments[at].Value switch
        {
            int value => value.ToString(CultureInfo.InvariantCulture),
            double value => value.ToString("R", CultureInfo.InvariantCulture),
            string text when double.TryParse(text, NumberStyles.Any, CultureInfo.InvariantCulture,
                out var parsed) => parsed.ToString("R", CultureInfo.InvariantCulture),
            _ => "0",
        };
    }

    private enum ValueKind { Unsupported, Text, Number, Bool }

    /// <summary>What a text box can round-trip. Everything else is skipped with a diagnostic rather
    /// than half-supported: a DateTime field needs a picker and a culture, and a form that silently
    /// dropped one would be worse than one that says so at compile time.</summary>
    private static ValueKind TypeOf(ITypeSymbol type)
    {
        var target = type is INamedTypeSymbol { IsGenericType: true, Name: "Nullable" } nullable
            ? nullable.TypeArguments[0]
            : type;
        return target.SpecialType switch
        {
            SpecialType.System_String => ValueKind.Text,
            SpecialType.System_Boolean => ValueKind.Bool,
            SpecialType.System_Int32 or SpecialType.System_Int64 or SpecialType.System_Int16
                or SpecialType.System_Byte or SpecialType.System_Single or SpecialType.System_Double
                or SpecialType.System_Decimal => ValueKind.Number,
            _ => ValueKind.Unsupported,
        };
    }

    private static string Camel(string name) =>
        name.Length == 0 ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static string Escape(string text) =>
        text.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class Field
    {
        public Field(string name, string local) { Name = name; Local = local; }

        public string Name { get; }
        /// <summary>The local the generated Create binds it to, so a cross-field rule can name it.</summary>
        public string Local { get; }
        public List<string> Rules { get; } = new();
        public List<(string Other, Location? At)> CompareRequests { get; } = new();
        public List<string> CompareWith { get; } = new();
    }

    private sealed class Model
    {
        public Model(string ns, string name, string formName, string fullName,
            List<Field> fields, List<Diagnostic> diagnostics)
        {
            Namespace = ns; Name = name; FormName = formName; FullName = fullName;
            Fields = fields; Diagnostics = diagnostics;
        }

        public string Namespace { get; }
        public string Name { get; }
        public string FormName { get; }
        public string FullName { get; }
        public List<Field> Fields { get; }
        public List<Diagnostic> Diagnostics { get; }
    }
}
