using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace eQuantic.UI.Generators;

/// <summary>
/// Writes the hydration manifest: one <c>[assembly: HydratedMember(...)]</c> per value a component
/// carries from its server render to the browser.
/// <para>
/// The server used to decide this for itself, by reflection, at run time. It named a value after the
/// field the C# compiler synthesized and kept whatever was not an interface, while eqc named the twin's
/// members by its own rule, so an auto-property crossed as <c>Downloads</c> into a twin that declares
/// <c>downloads</c> and never landed, and a captured primary-constructor parameter crossed as
/// <c>&lt;identity&gt;P</c>. The build knows every member's symbol, so the description is written here,
/// once, and the server and eqc both read it.
/// </para>
/// <para>
/// A type is described when its state can cross: when it prefetches, whatever it derives from (a
/// write-once component or an escape-hatch page alike). Every member it and its app-declared bases hold
/// crosses, except a delegate (the browser builds its own handlers) and a dependency the browser
/// resolves for itself (<see cref="CapabilityRule"/>, the rule the factory surface and eqc already
/// share). A type is named by its metadata name, so a private nested component is described too.
/// </para>
/// </summary>
[Generator]
public sealed class HydrationManifestGenerator : IIncrementalGenerator
{
    private const string PrefetchInterface = "eQuantic.UI.Primitives.IServerPrefetch";
    private const string Attribute = "global::eQuantic.UI.Primitives.HydratedMember";
    private const string Kind = "global::eQuantic.UI.Primitives.HydratedMemberKind";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var components = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, token) => Describe(ctx, token))
            .Where(static component => component is not null)
            .Collect();

        context.RegisterSourceOutput(components, static (spc, all) => Emit(spc, all));
    }

    /// <summary>One crossing value: the component, the type declaring the member, the member, its kind.</summary>
    private sealed class Entry
    {
        public Entry(string component, string declaringType, string member, string kind)
        {
            Component = component; DeclaringType = declaringType; Member = member; Kind = kind;
        }

        public string Component { get; }
        public string DeclaringType { get; }
        public string Member { get; }
        public string Kind { get; }
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<IReadOnlyList<Entry>?> all)
    {
        // A partial class is met once per declaration, so the same entries arrive more than once.
        var entries = all.Where(e => e is not null).SelectMany(e => e!)
            .GroupBy(e => (e.Component, e.DeclaringType, e.Member, e.Kind))
            .Select(g => g.First())
            .OrderBy(e => e.Component, System.StringComparer.Ordinal)
            .ThenBy(e => e.DeclaringType, System.StringComparer.Ordinal)
            .ThenBy(e => e.Member, System.StringComparer.Ordinal)
            .ToList();
        if (entries.Count == 0) return;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("// What each component carries from its server render to the browser. The server writes a page's");
        source.AppendLine("// state from these entries alone, and eqc writes each twin's adoption from them.");
        foreach (var entry in entries)
            source.AppendLine(
                $"[assembly: {Attribute}(\"{entry.Component}\", \"{entry.DeclaringType}\", "
                + $"\"{entry.Member}\", {Kind}.{entry.Kind})]");

        spc.AddSource("HydrationManifest.g.cs", source.ToString());
    }

    private static IReadOnlyList<Entry>? Describe(GeneratorSyntaxContext ctx, System.Threading.CancellationToken token)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, token) is not INamedTypeSymbol symbol) return null;
        if (symbol.IsAbstract || symbol.IsStatic) return null;
        if (!Prefetches(symbol)) return null;

        var component = MetadataName(symbol);
        var entries = new List<Entry>();
        for (var type = symbol; type is not null && IsDeclaredInSource(type); type = type.BaseType)
        {
            var declaring = MetadataName(type);
            foreach (var member in type.GetMembers())
            {
                token.ThrowIfCancellationRequested();
                if (member is not IFieldSymbol { IsStatic: false, IsConst: false } field) continue;
                if (Excluded(field.Type)) continue;

                // An auto-property's storage is a field the compiler declares for it: the property is
                // what crosses, read through its getter.
                if (field.IsImplicitlyDeclared)
                {
                    if (field.AssociatedSymbol is IPropertySymbol { IsStatic: false } property)
                        entries.Add(new Entry(component, declaring, property.Name, "Property"));
                    continue;
                }

                entries.Add(new Entry(component, declaring, field.Name, "Field"));
            }

            foreach (var parameter in CapturedParameters(type, ctx.SemanticModel.Compilation, token))
                if (!Excluded(parameter.Type))
                    entries.Add(new Entry(component, declaring, parameter.Name, "CapturedParameter"));
        }

        return entries;
    }

    /// <summary>A delegate never crosses, and neither does a dependency the browser resolves itself.</summary>
    private static bool Excluded(ITypeSymbol type) =>
        type.TypeKind == TypeKind.Delegate || CapabilityRule.IsDependency(type);

    /// <summary>
    /// The primary-constructor parameters the class captures, which is what makes the C# compiler give
    /// one a field: a reference from a member's body. A reference from a field or property initializer,
    /// or from the base type's arguments, runs during construction and is not a capture.
    /// </summary>
    private static IEnumerable<IParameterSymbol> CapturedParameters(
        INamedTypeSymbol type, Compilation compilation, System.Threading.CancellationToken token)
    {
        var declarations = type.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax(token))
            .OfType<TypeDeclarationSyntax>()
            .ToList();
        var primary = declarations.FirstOrDefault(d => d.ParameterList is not null);
        if (primary is null) return Enumerable.Empty<IParameterSymbol>();

        var model = compilation.GetSemanticModel(primary.SyntaxTree);
        var parameters = primary.ParameterList!.Parameters
            .Select(p => model.GetDeclaredSymbol(p, token))
            .OfType<IParameterSymbol>()
            .ToList();
        if (parameters.Count == 0) return Enumerable.Empty<IParameterSymbol>();

        var captured = new HashSet<IParameterSymbol>(SymbolEqualityComparer.Default);
        foreach (var declaration in declarations)
        {
            var declarationModel = compilation.GetSemanticModel(declaration.SyntaxTree);
            foreach (var identifier in declaration.DescendantNodes().OfType<IdentifierNameSyntax>())
            {
                if (!parameters.Any(p => p.Name == identifier.Identifier.ValueText)) continue;
                if (declarationModel.GetSymbolInfo(identifier, token).Symbol is not IParameterSymbol bound) continue;
                if (!parameters.Contains(bound, SymbolEqualityComparer.Default)) continue;
                if (RunsDuringConstruction(identifier)) continue;
                captured.Add(bound);
            }
        }

        return parameters.Where(p => captured.Contains(p));
    }

    /// <summary>Whether a reference sits where the constructor evaluates it: an initializer, or the base's arguments.</summary>
    private static bool RunsDuringConstruction(SyntaxNode reference)
    {
        foreach (var ancestor in reference.Ancestors())
        {
            switch (ancestor)
            {
                case BaseListSyntax:
                case FieldDeclarationSyntax:
                    return true;
                case PropertyDeclarationSyntax property:
                    return property.Initializer is { } initializer && initializer.Span.Contains(reference.Span);
                case MemberDeclarationSyntax:
                    return false;
            }
        }
        return false;
    }

    private static bool Prefetches(INamedTypeSymbol symbol) =>
        symbol.AllInterfaces.Any(i => i.ToDisplayString() == PrefetchInterface);

    /// <summary>
    /// The app's own types are described; a framework base's fields belong to the framework, and a
    /// referenced assembly's private members are not even visible to this compilation.
    /// </summary>
    private static bool IsDeclaredInSource(INamedTypeSymbol type) =>
        type.Locations.Any(location => location.IsInSource);

    /// <summary>
    /// The name the runtime gives the type's definition (<see cref="System.Type.FullName"/>): its
    /// namespace, its containing types joined by <c>+</c>, and the arity a generic one carries
    /// (<c>Shop.Grid`1</c>).
    /// </summary>
    private static string MetadataName(INamedTypeSymbol type)
    {
        var name = type.MetadataName;
        for (var outer = type.ContainingType; outer is not null; outer = outer.ContainingType)
            name = outer.MetadataName + "+" + name;
        var space = type.ContainingNamespace;
        return space is null || space.IsGlobalNamespace ? name : space.ToDisplayString() + "." + name;
    }
}
