/**
 * Every Primitives type an app can NAME resolves to a runtime export of the same name.
 *
 * eqc routes the whole `eQuantic.UI.Primitives` namespace to `@equantic/runtime` implicitly — that
 * is what lets the shared vocabulary work without an attribute on every type. The cost is that
 * adding a public class there silently promises an export, and the failure lands as far from the
 * cause as it gets: the page dies at hydration on `does not provide an export named 'X'` while SSR
 * keeps answering 200 with correct markup, so everything looks right until the screen is blank.
 * `RouteValues` shipped that way and took a page down.
 *
 * The C# side pins the QUESTION (`primitives-types.fixture.json`, regenerated by
 * `PrimitivesRuntimeExportTests`); this asks the module itself for the answer, because
 * `runtime-exports.ts` ends in `export * from './components'` and no amount of reading the file
 * text can see through a wildcard.
 */

import { describe, expect, it } from 'vitest';
import * as runtimeExports from './runtime-exports';
import primitivesTypes from './primitives-types.fixture.json';
import pinnedValues from './primitive-values.fixture.json';
import { ImageData, NetworkState, SpringSpec, WindowSizeClasses } from './primitive-values';

/**
 * Types that owe no export, each for a stated reason — a list of names, so the next one cannot slip
 * in unnoticed and so this reads as a decision rather than a backlog.
 */
const NO_TWIN_OWED = new Set([
  // Never in a page bundle: host and server plumbing, or an abstract base.
  'AbsentMotionSensor',
  'ComponentBoundary',
  'ComponentInstanceStore',
  'FlexNode',
  'VisualNodeExtensions',
  // DEAD C#: ButtonStyles.Resolve and ButtonRenderer.Draw have no callers — the resolved-style
  // path was superseded by the Box/StyleDiff one the realizers actually use. A twin here would be
  // mirroring code nobody runs; if that path ever comes back, so does its export.
  'ButtonStyle',
]);

describe('Primitives ⇄ runtime export parity', () => {
  it('every pinned Primitives type is exported, or listed with a reason', () => {
    const missing = (primitivesTypes as string[])
      .filter((name) => !NO_TWIN_OWED.has(name))
      .filter((name) => !(name in runtimeExports));

    expect(missing).toEqual([]);
  });

  // A name that got its export can leave the list. Without this the list only ever grows, and a
  // list that only grows stops meaning "these are the exceptions" and starts meaning nothing.
  it('nothing on the exception list is exported after all', () => {
    const stale = [...NO_TWIN_OWED].filter((name) => name in runtimeExports);

    expect(stale).toEqual([]);
  });

  // The one this whole file exists for.
  it('exports RouteValues, so a page can read its route', () => {
    expect('RouteValues' in runtimeExports).toBe(true);
  });
});

/**
 * The type-level check above proves the export EXISTS. This proves it says the same thing: a twin
 * is a mirror, and nothing else compares a mirror to its subject. `SpringSpec.Default` could change
 * in C# and the client would keep animating with the old numbers, silently, on the half of the
 * framework nobody runs in a debugger.
 *
 * The C# side writes the fixture (it is the source of these values); this asks the twin.
 */
describe('Primitives value twins carry the C# values', () => {
  it('SpringSpec.default is the C# SpringSpec.Default', () => {
    expect({
      stiffness: SpringSpec.default.stiffness,
      damping: SpringSpec.default.damping,
      mass: SpringSpec.default.mass,
    }).toEqual(pinnedValues.springDefault);
  });

  it('NetworkState.offline is the C# NetworkState.Offline', () => {
    expect({ online: NetworkState.offline.online, kind: NetworkState.offline.kind })
      .toEqual(pinnedValues.networkOffline);
  });

  // The BOUNDARIES, which is where an off-by-one between the two would live.
  it('WindowSizeClasses classifies the way C# does, thresholds included', () => {
    const w = pinnedValues.windowSizeClasses;
    expect(WindowSizeClasses.mediumMinDp).toBe(w.mediumMinDp);
    expect(WindowSizeClasses.expandedMinDp).toBe(w.expandedMinDp);
    expect(WindowSizeClasses.fromWidth(599)).toBe(w.atCompact);
    expect(WindowSizeClasses.fromWidth(600)).toBe(w.atMedium);
    expect(WindowSizeClasses.fromWidth(839)).toBe(w.belowExpanded);
    expect(WindowSizeClasses.fromWidth(840)).toBe(w.atExpanded);
  });

  it('ImageData reports its own size', () => {
    expect(new ImageData(new Uint8Array([1, 2, 3]), 'image/png').byteCount).toBe(3);
  });
});
