/**
 * Every Primitives type an app can NAME resolves to a runtime export of the same name.
 *
 * eqc routes the whole `eQuantic.UI.Primitives` namespace to `@equantic/runtime` implicitly — that
 * is what lets the shared vocabulary work without an attribute on every type. The cost is that
 * adding a public class there silently promises an export, and the failure lands as far from the
 * cause as it gets: the page dies at hydration on `does not provide an export named 'X'` while SSR
 * keeps answering 200 with correct markup, so everything looks right until the screen is blank.
 * `RouteValues` shipped that way and took a page down.
 *
 * The C# side pins the QUESTION (`primitives-types.fixture.json`, regenerated by
 * `PrimitivesRuntimeExportTests`); this asks the module itself for the answer, because
 * `runtime-exports.ts` ends in `export * from './components'` and no amount of reading the file
 * text can see through a wildcard.
 */

import { describe, expect, it } from 'vitest';
import * as runtimeExports from './runtime-exports';
import primitivesTypes from './primitives-types.fixture.json';

/**
 * Types with NO TypeScript twin at all, so no export can be owed yet — a list of names, so the next
 * one cannot slip in unnoticed and so this reads as a to-do rather than a decision.
 *
 * Host and server plumbing (`AbsentMotionSensor`, `ComponentBoundary`, `ComponentInstanceStore`,
 * `FlexNode`, `VisualNodeExtensions`) belongs here for good: it is never named from a page bundle.
 *
 * The REST are latent instances of the bug this file was written for. A page that names
 * `ImageData` after picking a photo, or `NetworkState` from a network subscription, dies at
 * hydration exactly the way a page reading its route did. Closing them means writing the twin, not
 * adding an export line, which is why they are listed rather than fixed in passing.
 */
const NO_TWIN_OWED = new Set([
  // Never in a page bundle.
  'AbsentMotionSensor',
  'ComponentBoundary',
  'ComponentInstanceStore',
  'FlexNode',
  'VisualNodeExtensions',
  // No twin yet — each of these is the same bug waiting for the page that names it.
  'ButtonStyle',
  'GeoLocation',
  'ImageData',
  'MotionReading',
  'MotionSpec',
  'MotionVector',
  'NetworkState',
  'SpringSpec',
  'WindowSizeClasses',
]);

describe('Primitives ⇄ runtime export parity', () => {
  it('every pinned Primitives type is exported, or listed with a reason', () => {
    const missing = (primitivesTypes as string[])
      .filter((name) => !NO_TWIN_OWED.has(name))
      .filter((name) => !(name in runtimeExports));

    expect(missing).toEqual([]);
  });

  // A name that got its export can leave the list. Without this the list only ever grows, and a
  // list that only grows stops meaning "these are the exceptions" and starts meaning nothing.
  it('nothing on the exception list is exported after all', () => {
    const stale = [...NO_TWIN_OWED].filter((name) => name in runtimeExports);

    expect(stale).toEqual([]);
  });

  // The one this whole file exists for.
  it('exports RouteValues, so a page can read its route', () => {
    expect('RouteValues' in runtimeExports).toBe(true);
  });
});
