import * as fs from 'fs';
import * as path from 'path';

/** Where a preview gets everything it needs, all of it produced by an ordinary `dotnet build`. */
export interface ProjectLayout {
  /** The directory holding the .csproj. */
  dir: string;
  /** The MSBuild-resolved reference list the SDK writes for eqc. */
  refsFile: string;
  /** Where the source generators wrote, for the configuration these references came from. */
  generatedDir: string;
  /** The browser runtime the compiled module imports from. */
  runtimePath: string;
}

export class ProjectNotReady extends Error {}

/** The nearest ancestor directory containing a .csproj — the project a file belongs to. */
export function findProjectDir(filePath: string): string | undefined {
  let dir = path.dirname(filePath);
  for (;;) {
    if (fs.existsSync(dir) && fs.readdirSync(dir).some((entry) => entry.endsWith('.csproj'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

/**
 * The intermediate output directory to preview from — `obj/<Configuration>/<tfm>`.
 *
 * Discovered rather than assumed: the configuration and target framework are the project's business,
 * and hardcoding `Debug/net10.0` breaks on the first person who previews a Release build. Newest
 * reference list wins, because that is the one the last build produced.
 */
function findIntermediateDir(projectDir: string): string | undefined {
  const objDir = path.join(projectDir, 'obj');
  if (!fs.existsSync(objDir)) return undefined;

  const candidates: { dir: string; stamp: number }[] = [];
  for (const configuration of fs.readdirSync(objDir)) {
    const configurationDir = path.join(objDir, configuration);
    if (!fs.statSync(configurationDir).isDirectory()) continue;

    for (const tfm of fs.readdirSync(configurationDir)) {
      const refs = path.join(configurationDir, tfm, 'equantic.refs.txt');
      // A zero-byte list is not a usable one: it means the reference set never resolved, and a
      // compilation built on it silently emits arguments in the wrong order.
      if (fs.existsSync(refs) && fs.statSync(refs).size > 0) {
        candidates.push({ dir: path.join(configurationDir, tfm), stamp: fs.statSync(refs).mtimeMs });
      }
    }
  }

  candidates.sort((a, b) => b.stamp - a.stamp);
  return candidates[0]?.dir;
}

/**
 * Everything the preview needs for this file, or a message saying which build step is missing.
 * Nothing here is generated by the extension: a preview stands on an ordinary build's output, so
 * "build the project once" is always the honest instruction when a piece is absent.
 */
export function resolveLayout(filePath: string, runtimeOverride: string): ProjectLayout {
  const dir = findProjectDir(filePath);
  if (!dir) throw new ProjectNotReady('This file is not inside a C# project — no .csproj in any parent directory.');

  const intermediate = findIntermediateDir(dir);
  if (!intermediate) {
    throw new ProjectNotReady(
      `No reference list found under ${path.join(dir, 'obj')}. Build the project once (dotnet build) — the eQuantic SDK writes equantic.refs.txt during the build, and the preview compiles against exactly those assemblies.`,
    );
  }

  const runtimePath = runtimeOverride || path.join(dir, 'wwwroot', '_equantic', 'runtime.js');
  if (!fs.existsSync(runtimePath)) {
    throw new ProjectNotReady(
      `The browser runtime is missing at ${runtimePath}. Build the project once so the SDK copies runtime.js into wwwroot/_equantic, or set equanticUI.runtimePath.`,
    );
  }

  return {
    dir,
    refsFile: path.join(intermediate, 'equantic.refs.txt'),
    generatedDir: path.join(intermediate, 'generated'),
    runtimePath,
  };
}
