import * as fs from 'fs';
import * as path from 'path';

/** Which realizer the project SHIPS with — read off its .csproj, never guessed from its code. */
export type ProjectTarget = 'web' | 'native' | 'unknown';

/** Where a preview gets everything it needs, all of it produced by an ordinary `dotnet build`. */
export interface ProjectLayout {
  /** The directory holding the .csproj. */
  dir: string;
  /** The MSBuild-resolved reference list the SDK writes for eqc. */
  refsFile: string;
  /** Where the source generators wrote, for the configuration these references came from. */
  generatedDir: string;
  /** The browser runtime the compiled module imports from. */
  runtimePath: string;
  /** web · native · unknown — what this project builds FOR, which is not what the preview renders
   * WITH (always the web realizer, of the same abstract tree). */
  target: ProjectTarget;
}

export class ProjectNotReady extends Error {}

/**
 * What the project builds for, read off the .csproj TEXT.
 *
 * The one reliable signal is which eQuantic MSBuild SDK the project goes through, and it is spelled
 * three ways in the wild: the `Sdk="…"` attribute (optionally `/versioned`), an `<Sdk Name="…"/>`
 * element, and — in a local checkout — an `<Import Project=".../Sdk/Sdk.props"/>` pair. All three are
 * plain substrings of the file.
 *
 * NATIVE IS TESTED FIRST, and not out of tidiness: `eQuantic.UI.Sdk.Native` CONTAINS
 * `eQuantic.UI.Sdk`, so the checks in the other order call every native project a web one. The same
 * prefix trap put the extension's release tag through the framework's pipeline once already.
 */
export function detectTarget(projectDir: string): ProjectTarget {
  for (const entry of fs.readdirSync(projectDir)) {
    if (!entry.endsWith('.csproj')) continue;
    const text = fs.readFileSync(path.join(projectDir, entry), 'utf8');
    if (text.includes('eQuantic.UI.Sdk.Native')) return 'native';
    if (text.includes('eQuantic.UI.Sdk')) return 'web';
  }
  return 'unknown';
}

/** The nearest ancestor directory containing a .csproj — the project a file belongs to. */
export function findProjectDir(filePath: string): string | undefined {
  let dir = path.dirname(filePath);
  for (;;) {
    if (fs.existsSync(dir) && fs.readdirSync(dir).some((entry) => entry.endsWith('.csproj'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

/**
 * The intermediate output directory to preview from — `obj/<Configuration>/<tfm>`.
 *
 * Discovered rather than assumed: the configuration and target framework are the project's business,
 * and hardcoding `Debug/net10.0` breaks on the first person who previews a Release build. Newest
 * reference list wins, because that is the one the last build produced.
 */
function findIntermediateDir(projectDir: string): string | undefined {
  const objDir = path.join(projectDir, 'obj');
  if (!fs.existsSync(objDir)) return undefined;

  const candidates: { dir: string; stamp: number }[] = [];
  for (const configuration of fs.readdirSync(objDir)) {
    const configurationDir = path.join(objDir, configuration);
    if (!fs.statSync(configurationDir).isDirectory()) continue;

    for (const tfm of fs.readdirSync(configurationDir)) {
      const refs = path.join(configurationDir, tfm, 'equantic.refs.txt');
      // A zero-byte list is not a usable one: it means the reference set never resolved, and a
      // compilation built on it silently emits arguments in the wrong order.
      if (fs.existsSync(refs) && fs.statSync(refs).size > 0) {
        candidates.push({ dir: path.join(configurationDir, tfm), stamp: fs.statSync(refs).mtimeMs });
      }
    }
  }

  candidates.sort((a, b) => b.stamp - a.stamp);
  return candidates[0]?.dir;
}

/**
 * Everything the preview needs for this file, or a message saying which build step is missing.
 * Nothing here is generated by the extension: a preview stands on an ordinary build's output, so
 * "build the project once" is always the honest instruction when a piece is absent.
 */
export function resolveLayout(filePath: string, runtimeOverride: string, bundledRuntime: string): ProjectLayout {
  const dir = findProjectDir(filePath);
  if (!dir) throw new ProjectNotReady('This file is not inside a C# project — no .csproj in any parent directory.');

  const target = detectTarget(dir);

  const intermediate = findIntermediateDir(dir);
  if (!intermediate) {
    // Both SDKs write the list during an ordinary build (the native one since it learned to), so
    // "build once" is the honest instruction for both — but only a current-enough native SDK does,
    // and saying so beats a user rebuilding forever against an older one.
    throw new ProjectNotReady(target === 'native'
      ? `No reference list found under ${path.join(dir, 'obj')}. Build the project once (dotnet build) — the native SDK writes equantic.refs.txt for tooling. If it still does not appear, the project is on an SDK older than 0.2.0-preview.31.`
      : `No reference list found under ${path.join(dir, 'obj')}. Build the project once (dotnet build) — the eQuantic SDK writes equantic.refs.txt during the build, and the preview compiles against exactly those assemblies.`);
  }

  // The project's own runtime wins — it matches the project's SDK version exactly. The bundled one
  // exists for projects that legitimately have none: a NATIVE project has no wwwroot, and its preview
  // still mounts the same abstract tree through the web realizer.
  const own = path.join(dir, 'wwwroot', '_equantic', 'runtime.js');
  const runtimePath = runtimeOverride || (fs.existsSync(own) ? own : bundledRuntime);
  if (!fs.existsSync(runtimePath)) {
    throw new ProjectNotReady(target === 'web'
      ? `The browser runtime is missing at ${own}. Build the project once so the SDK copies runtime.js into wwwroot/_equantic, or set equanticUI.runtimePath.`
      : `The bundled browser runtime is missing at ${runtimePath} — reinstall the extension, or set equanticUI.runtimePath.`);
  }

  return {
    dir,
    refsFile: path.join(intermediate, 'equantic.refs.txt'),
    generatedDir: path.join(intermediate, 'generated'),
    runtimePath,
    target,
  };
}
