<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <IsPackable>true</IsPackable>
        <PackageId>eQuantic.UI.Tailwind</PackageId>
        <Description>Tailwind CSS integration for eQuantic.UI using embedded Bun runtime.</Description>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\eQuantic.UI.Server\eQuantic.UI.Server.csproj" />
        <ProjectReference Include="..\eQuantic.UI.Compiler\eQuantic.UI.Compiler.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Build\eQuantic.UI.Tailwind.targets" PackagePath="build" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

</Project>