//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (the ResXFileCodeGenerator shape the IDE
//     writes beside Strings.resx). Manual changes will be lost on regeneration.
//     Add a key to Strings.resx and a property here (or let the IDE do both).
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace EQuanticApp.Resources
{
    internal class Strings
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        internal Strings() { }

        internal static global::System.Resources.ResourceManager ResourceManager =>
            resourceMan ??= new global::System.Resources.ResourceManager(
                "EQuanticApp.Resources.Strings", typeof(Strings).Assembly);

        internal static global::System.Globalization.CultureInfo? Culture { get; set; }

        internal static string Tagline
        {
            get { return ResourceManager.GetString("Tagline", Culture)!; }
        }

        internal static string CountedTimes
        {
            get { return ResourceManager.GetString("CountedTimes", Culture)!; }
        }
    }
}
