using System.Text;
using eQuantic.UI.Compiler.Models;

namespace eQuantic.UI.Compiler.CodeGen;

/// <summary>
/// Generates optimized CSS from StyleClass definitions
/// </summary>
public class CssEmitter
{
    private readonly StringBuilder _output = new();
    private readonly HashSet<string> _emittedClasses = new();
    
    /// <summary>
    /// Emit CSS for all StyleClass usages found in components
    /// </summary>
    public string Emit(IEnumerable<StyleClassUsage> usages)
    {
        _output.Clear();
        _emittedClasses.Clear();
        
        // Header comment
        _output.AppendLine("/* Generated by eQuantic.UI Compiler */");
        _output.AppendLine();
        
        // CSS custom properties (design tokens)
        EmitCssVariables();
        _output.AppendLine();
        
        // Emit styles for each unique StyleClass
        var uniqueUsages = usages
            .GroupBy(u => u.FullName)
            .Select(g => g.First());
        
        foreach (var usage in uniqueUsages)
        {
            if (!_emittedClasses.Contains(usage.ClassName))
            {
                // Note: In a real implementation, we would analyze the StyleClass
                // definition and emit its properties. For now, just emit placeholder.
                EmitStyleClassPlaceholder(usage);
                _emittedClasses.Add(usage.ClassName);
            }
        }
        
        return _output.ToString();
    }
    
    /// <summary>
    /// Emit CSS from a StyleClass definition (direct access)
    /// </summary>
    public string EmitStyleClass(string className, StyleClassProperties properties)
    {
        var sb = new StringBuilder();
        
        // Main class
        sb.AppendLine($".{className} {{");
        
        if (!string.IsNullOrEmpty(properties.Display))
            sb.AppendLine($"  display: {properties.Display};");
        if (!string.IsNullOrEmpty(properties.Position))
            sb.AppendLine($"  position: {properties.Position};");
        if (!string.IsNullOrEmpty(properties.BackgroundColor))
            sb.AppendLine($"  background-color: {properties.BackgroundColor};");
        if (!string.IsNullOrEmpty(properties.Color))
            sb.AppendLine($"  color: {properties.Color};");
        if (!string.IsNullOrEmpty(properties.Padding))
            sb.AppendLine($"  padding: {properties.Padding};");
        if (!string.IsNullOrEmpty(properties.Margin))
            sb.AppendLine($"  margin: {properties.Margin};");
        if (properties.BorderRadius.HasValue)
            sb.AppendLine($"  border-radius: {properties.BorderRadius}px;");
        if (!string.IsNullOrEmpty(properties.FontSize))
            sb.AppendLine($"  font-size: {properties.FontSize};");
        if (!string.IsNullOrEmpty(properties.FontWeight))
            sb.AppendLine($"  font-weight: {properties.FontWeight};");
        if (!string.IsNullOrEmpty(properties.Cursor))
            sb.AppendLine($"  cursor: {properties.Cursor};");
        if (!string.IsNullOrEmpty(properties.BoxShadow))
            sb.AppendLine($"  box-shadow: {properties.BoxShadow};");
        if (!string.IsNullOrEmpty(properties.Transition))
            sb.AppendLine($"  transition: {properties.Transition};");
        
        sb.AppendLine("}");
        
        // Hover pseudo-class
        if (properties.Hover != null)
        {
            sb.AppendLine($".{className}:hover {{");
            EmitPseudoClassProperties(sb, properties.Hover);
            sb.AppendLine("}");
        }
        
        // Active pseudo-class
        if (properties.Active != null)
        {
            sb.AppendLine($".{className}:active {{");
            EmitPseudoClassProperties(sb, properties.Active);
            sb.AppendLine("}");
        }
        
        // Focus pseudo-class
        if (properties.Focus != null)
        {
            sb.AppendLine($".{className}:focus {{");
            EmitPseudoClassProperties(sb, properties.Focus);
            sb.AppendLine("}");
        }
        
        // Media queries
        if (properties.MediaQueries != null)
        {
            foreach (var (breakpoint, mediaProps) in properties.MediaQueries)
            {
                sb.AppendLine($"@media (max-width: {breakpoint}px) {{");
                sb.AppendLine($"  .{className} {{");
                EmitPseudoClassProperties(sb, mediaProps, "    ");
                sb.AppendLine("  }");
                sb.AppendLine("}");
            }
        }
        
        return sb.ToString();
    }
    
    private void EmitPseudoClassProperties(StringBuilder sb, StyleClassProperties props, string indent = "  ")
    {
        if (!string.IsNullOrEmpty(props.BackgroundColor))
            sb.AppendLine($"{indent}background-color: {props.BackgroundColor};");
        if (!string.IsNullOrEmpty(props.Color))
            sb.AppendLine($"{indent}color: {props.Color};");
        if (!string.IsNullOrEmpty(props.BoxShadow))
            sb.AppendLine($"{indent}box-shadow: {props.BoxShadow};");
        if (!string.IsNullOrEmpty(props.Transform))
            sb.AppendLine($"{indent}transform: {props.Transform};");
    }
    
    private void EmitCssVariables()
    {
        _output.AppendLine(":root {");
        _output.AppendLine("  /* Primary colors */");
        _output.AppendLine("  --color-primary: #3b82f6;");
        _output.AppendLine("  --color-primary-light: #60a5fa;");
        _output.AppendLine("  --color-primary-dark: #2563eb;");
        _output.AppendLine();
        _output.AppendLine("  /* Secondary colors */");
        _output.AppendLine("  --color-secondary: #6b7280;");
        _output.AppendLine("  --color-secondary-light: #9ca3af;");
        _output.AppendLine("  --color-secondary-dark: #4b5563;");
        _output.AppendLine();
        _output.AppendLine("  /* Semantic colors */");
        _output.AppendLine("  --color-success: #22c55e;");
        _output.AppendLine("  --color-warning: #f59e0b;");
        _output.AppendLine("  --color-error: #ef4444;");
        _output.AppendLine("  --color-info: #3b82f6;");
        _output.AppendLine("}");
    }
    
    private void EmitStyleClassPlaceholder(StyleClassUsage usage)
    {
        _output.AppendLine($"/* {usage.FullName} */");
        _output.AppendLine($".{usage.ClassName} {{");
        _output.AppendLine("  /* Properties to be extracted from StyleClass definition */");
        _output.AppendLine("}");
        _output.AppendLine();
    }
}

/// <summary>
/// Properties for CSS emission (simplified model for code generation)
/// </summary>
public class StyleClassProperties
{
    public string? Display { get; set; }
    public string? Position { get; set; }
    public string? BackgroundColor { get; set; }
    public string? Color { get; set; }
    public string? Padding { get; set; }
    public string? Margin { get; set; }
    public int? BorderRadius { get; set; }
    public string? FontSize { get; set; }
    public string? FontWeight { get; set; }
    public string? Cursor { get; set; }
    public string? BoxShadow { get; set; }
    public string? Transition { get; set; }
    public string? Transform { get; set; }
    
    public StyleClassProperties? Hover { get; set; }
    public StyleClassProperties? Active { get; set; }
    public StyleClassProperties? Focus { get; set; }
    
    public Dictionary<int, StyleClassProperties>? MediaQueries { get; set; }
}
