<Project>
    <Import Project="../../src/eQuantic.UI.Sdk/Sdk/Sdk.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\eQuantic.UI.Material\eQuantic.UI.Material.csproj" />
    </ItemGroup>

    <Import Project="../../src/eQuantic.UI.Sdk/Sdk/Sdk.targets" />

    <!-- Import Material targets for CSS generation -->
    <Import Project="../../src/eQuantic.UI.Material/Build/eQuantic.UI.Material.targets" />
</Project>