//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (the ResXFileCodeGenerator shape the IDE
//     writes beside Strings.resx). Manual changes will be lost on regeneration.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace EQuanticNativeApp.Resources
{
    internal class Strings
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        internal Strings() { }

        internal static global::System.Resources.ResourceManager ResourceManager =>
            resourceMan ??= new global::System.Resources.ResourceManager(
                "EQuanticNativeApp.Resources.Strings", typeof(Strings).Assembly);

        internal static global::System.Globalization.CultureInfo? Culture { get; set; }

        internal static string PressedTimes
        {
            get { return ResourceManager.GetString("PressedTimes", Culture)!; }
        }

        internal static string CountUp
        {
            get { return ResourceManager.GetString("CountUp", Culture)!; }
        }
    }
}
