using Android.Content;
using Android.Security.Keystore;
using eQuantic.UI.Primitives;
using Java.Security;
using Javax.Crypto;
using Javax.Crypto.Spec;

namespace eQuantic.UI.Native.Shell.Android;

/// <summary>
/// The Android KeyStore, standing behind an ordinary preferences file.
/// <para>
/// The secret never leaves the app as plaintext: a hardware-backed AES key lives in
/// <c>AndroidKeyStore</c> — where the key material is not readable by anything, including this
/// process — and only the ciphertext lands in a preferences file. That is exactly what AndroidX's
/// <c>EncryptedSharedPreferences</c> does, written here directly because the platform already
/// provides every piece and the framework does not take a dependency for something the OS ships.
/// </para>
/// <para>
/// AES/GCM: authenticated, so a tampered value fails to decrypt rather than decrypting to garbage.
/// The IV is generated by the cipher (never reused, never chosen here — a repeated GCM IV under one
/// key is the mistake that breaks the whole construction) and stored in front of the ciphertext,
/// which is safe and standard: an IV is public, it just must not repeat.
/// </para>
/// <para>
/// Every failure answers null. A key can be invalidated by the platform — a new lock screen, a
/// restore onto another device — and every value under it becomes permanently unreadable. The
/// contract already says a null read means "sign in again", which is the only thing to do about it.
/// </para>
/// </summary>
internal sealed class AndroidSecretStore : ISecretStore
{
    private const string File = "equantic.ui.secret-store";
    private const string KeyAlias = "equantic.ui.secret-key";
    private const string Transformation = "AES/GCM/NoPadding";
    private const int TagBits = 128;
    private const int IvBytes = 12;

    private static ISharedPreferences? Preferences =>
        PhotonActivity.Current?.GetSharedPreferences(File, FileCreationMode.Private);

    /// <summary>The KeyStore-held AES key, created on first use and reused forever after.</summary>
    private static IKey? Key()
    {
        try
        {
            var store = KeyStore.GetInstance("AndroidKeyStore");
            if (store is null) return null;
            store.Load(null);
            if (store.GetKey(KeyAlias, null) is { } existing) return existing;

            var generator = KeyGenerator.GetInstance(KeyProperties.KeyAlgorithmAes, "AndroidKeyStore");
            if (generator is null) return null;
            generator.Init(new KeyGenParameterSpec.Builder(
                    KeyAlias, KeyStorePurpose.Encrypt | KeyStorePurpose.Decrypt)
                .SetBlockModes(KeyProperties.BlockModeGcm)!
                .SetEncryptionPaddings(KeyProperties.EncryptionPaddingNone)!
                .Build());
            return generator.GenerateKey();
        }
        catch (Java.Lang.Exception)
        {
            // No KeyStore, or a key the platform has invalidated — either way there is no vault.
            return null;
        }
    }

    public string? Get(string key)
    {
        var stored = Preferences?.GetString(key, null);
        if (stored is null || Key() is not { } aesKey) return null;

        try
        {
            var blob = Convert.FromBase64String(stored);
            if (blob.Length <= IvBytes) return null;

            var cipher = Cipher.GetInstance(Transformation);
            if (cipher is null) return null;
            cipher.Init(CipherMode.DecryptMode, aesKey, new GCMParameterSpec(TagBits, blob, 0, IvBytes));

            var plain = cipher.DoFinal(blob, IvBytes, blob.Length - IvBytes);
            return plain is null ? null : System.Text.Encoding.UTF8.GetString(plain);
        }
        catch (Java.Lang.Exception)
        {
            // Tampered, or encrypted under a key the platform has since invalidated.
            return null;
        }
        catch (FormatException)
        {
            return null;
        }
    }

    public void Set(string key, string value)
    {
        if (Key() is not { } aesKey || Preferences?.Edit() is not { } editor) return;

        try
        {
            var cipher = Cipher.GetInstance(Transformation);
            if (cipher is null) return;
            cipher.Init(CipherMode.EncryptMode, aesKey);

            var iv = cipher.GetIV();
            var encrypted = cipher.DoFinal(System.Text.Encoding.UTF8.GetBytes(value));
            if (iv is null || encrypted is null) return;

            var blob = new byte[iv.Length + encrypted.Length];
            iv.CopyTo(blob, 0);
            encrypted.CopyTo(blob, iv.Length);

            editor.PutString(key, Convert.ToBase64String(blob));
            editor.Apply();
        }
        catch (Java.Lang.Exception)
        {
            /* no vault, no write — and nothing plaintext left behind */
        }
    }

    /// <summary>What a sign-out calls.</summary>
    public void Remove(string key)
    {
        var editor = Preferences?.Edit();
        if (editor is null) return;
        editor.Remove(key);
        editor.Apply();
    }
}
