//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (the ResXFileCodeGenerator shape the IDE
//     writes beside SdkResources.resx). Manual changes will be lost on regeneration.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace eQuantic.UI.Components
{
    /// <summary>
    /// The SDK's own strings, reached exactly as an app reaches its own: through the generated
    /// accessor. On server and native this is the real ResourceManager over satellite assemblies;
    /// on the web eqc REWRITES every property below into a catalog lookup (I18N-PLAN D2/D14), so
    /// the build machine's language is never baked into a bundle.
    /// </summary>
    internal class SdkResources
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        internal SdkResources() { }

        internal static global::System.Resources.ResourceManager ResourceManager =>
            resourceMan ??= new global::System.Resources.ResourceManager(
                "eQuantic.UI.Components.SdkResources", typeof(SdkResources).Assembly);

        internal static global::System.Globalization.CultureInfo? Culture { get; set; }

        internal static string Dismiss
        {
            get { return ResourceManager.GetString("Dismiss", Culture)!; }
        }

        internal static string CookieConsentTitle
        {
            get { return ResourceManager.GetString("CookieConsentTitle", Culture)!; }
        }

        internal static string CookieConsentBody
        {
            get { return ResourceManager.GetString("CookieConsentBody", Culture)!; }
        }

        internal static string AcceptCookies
        {
            get { return ResourceManager.GetString("AcceptCookies", Culture)!; }
        }

        internal static string RejectCookies
        {
            get { return ResourceManager.GetString("RejectCookies", Culture)!; }
        }

        internal static string PrivacyPolicy
        {
            get { return ResourceManager.GetString("PrivacyPolicy", Culture)!; }
        }

        internal static string Remove
        {
            get { return ResourceManager.GetString("Remove", Culture)!; }
        }

        internal static string SearchPlaceholder
        {
            get { return ResourceManager.GetString("SearchPlaceholder", Culture)!; }
        }

        internal static string ClearSearch
        {
            get { return ResourceManager.GetString("ClearSearch", Culture)!; }
        }

        internal static string Find
        {
            get { return ResourceManager.GetString("Find", Culture)!; }
        }

        internal static string PreviousMatch
        {
            get { return ResourceManager.GetString("PreviousMatch", Culture)!; }
        }

        internal static string NextMatch
        {
            get { return ResourceManager.GetString("NextMatch", Culture)!; }
        }

        internal static string Spreadsheet
        {
            get { return ResourceManager.GetString("Spreadsheet", Culture)!; }
        }

        internal static string Back
        {
            get { return ResourceManager.GetString("Back", Culture)!; }
        }

        internal static string NothingSelected
        {
            get { return ResourceManager.GetString("NothingSelected", Culture)!; }
        }

        internal static string ShowAsTable
        {
            get { return ResourceManager.GetString("ShowAsTable", Culture)!; }
        }

        internal static string ShowAsChart
        {
            get { return ResourceManager.GetString("ShowAsChart", Culture)!; }
        }
    
        internal static string PreviousMonth
        {
            get { return ResourceManager.GetString("PreviousMonth", Culture)!; }
        }

        internal static string NextMonth
        {
            get { return ResourceManager.GetString("NextMonth", Culture)!; }
        }

        internal static string Today
        {
            get { return ResourceManager.GetString("Today", Culture)!; }
        }


        internal static string ChooseDate
        {
            get { return ResourceManager.GetString("ChooseDate", Culture)!; }
        }

        internal static string ChooseTime
        {
            get { return ResourceManager.GetString("ChooseTime", Culture)!; }
        }

        internal static string DateFormatLetters
        {
            get { return ResourceManager.GetString("DateFormatLetters", Culture)!; }
        }
}
}
