namespace eQuantic.UI.Native.Engine.Metal;

/// <summary>
/// The Metal shader source — GENERATED by Slang from the ONE normative file
/// (<c>eQuantic.UI.Native.Engine/Shaders/Sdf.slang</c>, itself a transliteration of <c>Sdf.cs</c>,
/// <c>Paint.ColorAt</c> and <c>ColorSpace</c>). Regenerate with <c>scripts/generate-shaders.sh</c>;
/// the same source emits the committed SPIR-V for the future Vulkan backend (plan D3). The device
/// still compiles MSL→binary at init (newLibraryWithSource) — the offline metallib step joins the
/// packaging work; pipeline creation remains once-per-device (D5).
/// </summary>
internal static class MetalShaders
{
    /// <summary>The Slang-generated MSL (embedded at build; see Shaders/Sdf.slang + generate-shaders.sh).</summary>
    public static readonly string Source = LoadGenerated();

    private static string LoadGenerated()
    {
        using var stream = typeof(MetalShaders).Assembly.GetManifestResourceStream("Photon.Sdf.metal")
            ?? throw new InvalidOperationException("Embedded shader 'Photon.Sdf.metal' missing — regenerate via scripts/generate-shaders.sh.");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
