using System.Runtime.InteropServices;

namespace eQuantic.UI.Native.Shell.Windows;

/// <summary>
/// The slice of Win32 a Photon window stands on — user32, gdi32, kernel32, dwmapi and imm32 —
/// as typed <c>LibraryImport</c> externs over the C ABI, the same "slim owned bindings" the Apple
/// shells use for objc_msgSend and the Vulkan backend uses for the loader. Nothing here is
/// generated by a binding framework and nothing is third-party: every function is exported by a
/// DLL that ships with Windows, and every constant is spelled from the SDK headers beside the call
/// that uses it.
/// </summary>
internal static unsafe partial class Win32
{
    private const string User32 = "user32.dll";
    private const string Gdi32 = "gdi32.dll";
    private const string Kernel32 = "kernel32.dll";
    private const string Dwmapi = "dwmapi.dll";
    private const string Imm32 = "imm32.dll";
    private const string Shell32 = "shell32.dll";

    // ---- Window styles ------------------------------------------------------------------------

    public const uint WS_OVERLAPPED = 0x00000000;
    public const uint WS_CAPTION = 0x00C00000;
    public const uint WS_SYSMENU = 0x00080000;
    public const uint WS_THICKFRAME = 0x00040000;
    public const uint WS_MINIMIZEBOX = 0x00020000;
    public const uint WS_MAXIMIZEBOX = 0x00010000;
    public const uint WS_OVERLAPPEDWINDOW =
        WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX;
    public const uint WS_EX_APPWINDOW = 0x00040000;

    public const uint CS_HREDRAW = 0x0002;
    public const uint CS_VREDRAW = 0x0001;

    public const int CW_USEDEFAULT = unchecked((int)0x80000000);

    public const int SW_SHOW = 5;

    // ---- Messages -----------------------------------------------------------------------------

    public const uint WM_DESTROY = 0x0002;
    public const uint WM_SIZE = 0x0005;
    public const uint WM_ACTIVATE = 0x0006;
    public const uint WM_SETFOCUS = 0x0007;
    public const uint WM_KILLFOCUS = 0x0008;
    public const uint WM_PAINT = 0x000F;
    public const uint WM_CLOSE = 0x0010;
    public const uint WM_QUIT = 0x0012;
    public const uint WM_ERASEBKGND = 0x0014;
    public const uint WM_SETTINGCHANGE = 0x001A;
    public const uint WM_SETCURSOR = 0x0020;
    public const uint WM_GETMINMAXINFO = 0x0024;
    public const uint WM_GETOBJECT = 0x003D;
    public const uint WM_COPYDATA = 0x004A;
    public const uint WM_NCCALCSIZE = 0x0083;
    public const uint WM_NCHITTEST = 0x0084;
    public const uint WM_NCMOUSEMOVE = 0x00A0;
    public const uint WM_NCLBUTTONDOWN = 0x00A1;
    public const uint WM_NCLBUTTONUP = 0x00A2;
    public const uint WM_NCLBUTTONDBLCLK = 0x00A3;
    public const uint WM_NCMOUSELEAVE = 0x02A2;
    public const uint WM_KEYDOWN = 0x0100;
    public const uint WM_KEYUP = 0x0101;
    public const uint WM_CHAR = 0x0102;
    public const uint WM_SYSKEYDOWN = 0x0104;
    public const uint WM_SYSKEYUP = 0x0105;
    public const uint WM_SYSCHAR = 0x0106;
    public const uint WM_IME_STARTCOMPOSITION = 0x010D;
    public const uint WM_IME_ENDCOMPOSITION = 0x010E;
    public const uint WM_IME_COMPOSITION = 0x010F;
    public const uint WM_SYSCOMMAND = 0x0112;
    public const uint WM_TIMER = 0x0113;
    public const uint WM_MOUSEMOVE = 0x0200;
    public const uint WM_LBUTTONDOWN = 0x0201;
    public const uint WM_LBUTTONUP = 0x0202;
    public const uint WM_RBUTTONDOWN = 0x0204;
    public const uint WM_RBUTTONUP = 0x0205;
    public const uint WM_MOUSEWHEEL = 0x020A;
    public const uint WM_MOUSEHWHEEL = 0x020E;
    public const uint WM_ENTERSIZEMOVE = 0x0231;
    public const uint WM_EXITSIZEMOVE = 0x0232;
    public const uint WM_MOUSELEAVE = 0x02A3;
    public const uint WM_DPICHANGED = 0x02E0;
    public const uint WM_THEMECHANGED = 0x031A;

    public const nuint SC_MINIMIZE = 0xF020;
    public const nuint SC_MAXIMIZE = 0xF030;
    public const nuint SC_CLOSE = 0xF060;
    public const nuint SC_RESTORE = 0xF120;

    public const nuint SIZE_MINIMIZED = 1;

    // ---- Hit testing --------------------------------------------------------------------------

    public const nint HTNOWHERE = 0;
    public const nint HTCLIENT = 1;
    public const nint HTCAPTION = 2;
    public const nint HTMINBUTTON = 8;
    public const nint HTMAXBUTTON = 9;
    public const nint HTLEFT = 10;
    public const nint HTRIGHT = 11;
    public const nint HTTOP = 12;
    public const nint HTTOPLEFT = 13;
    public const nint HTTOPRIGHT = 14;
    public const nint HTBOTTOM = 15;
    public const nint HTBOTTOMLEFT = 16;
    public const nint HTBOTTOMRIGHT = 17;
    public const nint HTCLOSE = 20;

    // ---- Message pump -------------------------------------------------------------------------

    public const uint PM_REMOVE = 0x0001;
    public const uint QS_ALLINPUT = 0x04FF;
    public const uint MWMO_INPUTAVAILABLE = 0x0004;

    // ---- System metrics / parameters ----------------------------------------------------------

    public const int SM_CXPADDEDBORDER = 92;
    public const int SM_CYSIZEFRAME = 33;
    public const uint SPI_GETWHEELSCROLLLINES = 0x0068;
    public const uint MONITOR_DEFAULTTOPRIMARY = 0x00000001;
    public const uint MONITOR_DEFAULTTONEAREST = 0x00000002;

    public const uint SWP_NOZORDER = 0x0004;
    public const uint SWP_NOACTIVATE = 0x0010;
    public const uint SWP_FRAMECHANGED = 0x0020;

    // ---- DPI ----------------------------------------------------------------------------------

    /// <summary>DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 — the one under which a window is told
    /// about every DPI change, its own non-client area included.</summary>
    public static readonly IntPtr DpiAwarenessPerMonitorV2 = new(-4);
    public const float BaseDpi = 96f;

    // ---- Cursors ------------------------------------------------------------------------------

    public const int IDC_ARROW = 32512;
    public const int IDC_IBEAM = 32513;
    public const int IDC_CROSS = 32515;
    public const int IDC_SIZEWE = 32644;
    public const int IDC_SIZENS = 32645;
    public const int IDC_NO = 32648;
    public const int IDC_HAND = 32649;

    // ---- Mouse tracking -----------------------------------------------------------------------

    public const uint TME_LEAVE = 0x00000002;
    public const uint TME_NONCLIENT = 0x00000010;
    public const int WHEEL_DELTA = 120;
    public const uint WHEEL_PAGESCROLL = uint.MaxValue;

    // ---- Keyboard -----------------------------------------------------------------------------

    public const int VK_SHIFT = 0x10;
    public const int VK_CONTROL = 0x11;
    public const int VK_MENU = 0x12;
    public const uint MAPVK_VK_TO_CHAR = 2;

    // ---- IME ----------------------------------------------------------------------------------

    public const uint GCS_COMPSTR = 0x0008;
    public const uint GCS_RESULTSTR = 0x0800;
    public const uint CFS_POINT = 0x0002;
    public const uint CFS_CANDIDATEPOS = 0x0040;
    public const uint IACE_DEFAULT = 0x0010;

    // ---- Clipboard ----------------------------------------------------------------------------

    public const uint CF_UNICODETEXT = 13;
    public const uint GMEM_MOVEABLE = 0x0002;

    // ---- DWM ----------------------------------------------------------------------------------

    public const uint DWMWA_USE_IMMERSIVE_DARK_MODE = 20;

    // ---- Console / locale ---------------------------------------------------------------------

    public const uint ATTACH_PARENT_PROCESS = 0xFFFFFFFF;
    public const uint MUI_LANGUAGE_NAME = 0x8;

    // ---- Structs ------------------------------------------------------------------------------

    [StructLayout(LayoutKind.Sequential)]
    public struct POINT
    {
        public int X;
        public int Y;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct RECT
    {
        public int Left;
        public int Top;
        public int Right;
        public int Bottom;

        public int Width => Right - Left;
        public int Height => Bottom - Top;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct WNDCLASSEXW
    {
        public uint Size;
        public uint Style;
        public IntPtr WndProc;
        public int ClassExtra;
        public int WindowExtra;
        public IntPtr Instance;
        public IntPtr Icon;
        public IntPtr Cursor;
        public IntPtr Background;
        public IntPtr MenuName;
        public IntPtr ClassName;
        public IntPtr IconSmall;
    }

    /// <summary>The SDK's MSG carries a trailing <c>lPrivate</c> the older declarations omit; the
    /// pump writes the whole structure, so the field is here to keep the stack honest.</summary>
    [StructLayout(LayoutKind.Sequential)]
    public struct MSG
    {
        public IntPtr Hwnd;
        public uint Message;
        public nuint WParam;
        public nint LParam;
        public uint Time;
        public POINT Point;
        public uint Private;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct MINMAXINFO
    {
        public POINT Reserved;
        public POINT MaxSize;
        public POINT MaxPosition;
        public POINT MinTrackSize;
        public POINT MaxTrackSize;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct PAINTSTRUCT
    {
        public IntPtr Hdc;
        public int Erase;
        public RECT Paint;
        public int Restore;
        public int IncUpdate;
        public fixed byte Reserved[32];
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct BITMAPINFOHEADER
    {
        public uint Size;
        public int Width;
        public int Height;
        public ushort Planes;
        public ushort BitCount;
        public uint Compression;
        public uint SizeImage;
        public int XPelsPerMeter;
        public int YPelsPerMeter;
        public uint ClrUsed;
        public uint ClrImportant;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct TRACKMOUSEEVENT
    {
        public uint Size;
        public uint Flags;
        public IntPtr Track;
        public uint HoverTime;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct NCCALCSIZE_PARAMS
    {
        public RECT Rect0;
        public RECT Rect1;
        public RECT Rect2;
        public IntPtr Position;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct COPYDATASTRUCT
    {
        public nuint Data;
        public uint Size;
        public IntPtr Bytes;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct COMPOSITIONFORM
    {
        public uint Style;
        public POINT CurrentPos;
        public RECT Area;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct CANDIDATEFORM
    {
        public uint Index;
        public uint Style;
        public POINT CurrentPos;
        public RECT Area;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct MONITORINFO
    {
        public uint Size;
        public RECT Monitor;
        public RECT Work;
        public uint Flags;
    }

    // ---- user32 -------------------------------------------------------------------------------

    [LibraryImport(User32, SetLastError = true)]
    public static partial ushort RegisterClassExW(WNDCLASSEXW* wndClass);

    [LibraryImport(User32, SetLastError = true, StringMarshalling = StringMarshalling.Utf16)]
    public static partial IntPtr CreateWindowExW(uint exStyle, string className, string windowName,
        uint style, int x, int y, int width, int height, IntPtr parent, IntPtr menu, IntPtr instance,
        IntPtr param);

    [LibraryImport(User32)]
    public static partial nint DefWindowProcW(IntPtr hwnd, uint message, nuint wParam, nint lParam);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool DestroyWindow(IntPtr hwnd);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ShowWindow(IntPtr hwnd, int command);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool PeekMessageW(MSG* message, IntPtr hwnd, uint filterMin, uint filterMax, uint remove);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool TranslateMessage(MSG* message);

    [LibraryImport(User32)]
    public static partial nint DispatchMessageW(MSG* message);

    [LibraryImport(User32)]
    public static partial uint MsgWaitForMultipleObjectsEx(uint count, IntPtr* handles, uint milliseconds,
        uint wakeMask, uint flags);

    [LibraryImport(User32)]
    public static partial void PostQuitMessage(int exitCode);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool PostMessageW(IntPtr hwnd, uint message, nuint wParam, nint lParam);

    [LibraryImport(User32)]
    public static partial nint SendMessageW(IntPtr hwnd, uint message, nuint wParam, nint lParam);

    [LibraryImport(User32, StringMarshalling = StringMarshalling.Utf16)]
    public static partial IntPtr FindWindowW(string? className, string? windowName);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GetClientRect(IntPtr hwnd, RECT* rect);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GetWindowRect(IntPtr hwnd, RECT* rect);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool SetWindowPos(IntPtr hwnd, IntPtr insertAfter, int x, int y, int width,
        int height, uint flags);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool AdjustWindowRectExForDpi(RECT* rect, uint style,
        [MarshalAs(UnmanagedType.Bool)] bool menu, uint exStyle, uint dpi);

    [LibraryImport(User32)]
    public static partial uint GetDpiForWindow(IntPtr hwnd);

    [LibraryImport(User32)]
    public static partial uint GetDpiForSystem();

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool SetProcessDpiAwarenessContext(IntPtr context);

    [LibraryImport(User32)]
    public static partial int GetSystemMetricsForDpi(int index, uint dpi);

    [LibraryImport(User32, SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool SystemParametersInfoW(uint action, uint parameter, void* value, uint winIni);

    [LibraryImport(User32)]
    public static partial IntPtr MonitorFromPoint(POINT point, uint flags);

    [LibraryImport(User32)]
    public static partial IntPtr MonitorFromWindow(IntPtr hwnd, uint flags);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GetMonitorInfoW(IntPtr monitor, MONITORINFO* info);

    [LibraryImport(User32)]
    public static partial IntPtr GetDC(IntPtr hwnd);

    [LibraryImport(User32)]
    public static partial int ReleaseDC(IntPtr hwnd, IntPtr hdc);

    [LibraryImport(User32)]
    public static partial IntPtr BeginPaint(IntPtr hwnd, PAINTSTRUCT* paint);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool EndPaint(IntPtr hwnd, PAINTSTRUCT* paint);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ValidateRect(IntPtr hwnd, RECT* rect);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool InvalidateRect(IntPtr hwnd, RECT* rect, [MarshalAs(UnmanagedType.Bool)] bool erase);

    [LibraryImport(User32)]
    public static partial IntPtr SetCapture(IntPtr hwnd);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ReleaseCapture();

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool TrackMouseEvent(TRACKMOUSEEVENT* track);

    [LibraryImport(User32)]
    public static partial short GetKeyState(int virtualKey);

    [LibraryImport(User32)]
    public static partial uint MapVirtualKeyW(uint code, uint mapType);

    [LibraryImport(User32)]
    public static partial IntPtr LoadCursorW(IntPtr instance, IntPtr name);

    [LibraryImport(User32)]
    public static partial IntPtr SetCursor(IntPtr cursor);

    [LibraryImport(User32)]
    public static partial nuint SetTimer(IntPtr hwnd, nuint id, uint elapse, IntPtr proc);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool KillTimer(IntPtr hwnd, nuint id);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GetCursorPos(POINT* point);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ScreenToClient(IntPtr hwnd, POINT* point);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ClientToScreen(IntPtr hwnd, POINT* point);

    [LibraryImport(User32)]
    public static partial uint GetDoubleClickTime();

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool IsZoomed(IntPtr hwnd);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool OpenClipboard(IntPtr owner);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool CloseClipboard();

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool EmptyClipboard();

    [LibraryImport(User32)]
    public static partial IntPtr GetClipboardData(uint format);

    [LibraryImport(User32)]
    public static partial IntPtr SetClipboardData(uint format, IntPtr memory);

    [LibraryImport(User32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool IsClipboardFormatAvailable(uint format);

    [LibraryImport(User32)]
    public static partial IntPtr LoadIconW(IntPtr instance, IntPtr name);

    // ---- kernel32 -----------------------------------------------------------------------------

    [LibraryImport(Kernel32, StringMarshalling = StringMarshalling.Utf16)]
    public static partial IntPtr GetModuleHandleW(string? moduleName);

    [LibraryImport(Kernel32)]
    public static partial IntPtr GlobalAlloc(uint flags, nuint bytes);

    [LibraryImport(Kernel32)]
    public static partial IntPtr GlobalLock(IntPtr memory);

    [LibraryImport(Kernel32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GlobalUnlock(IntPtr memory);

    [LibraryImport(Kernel32)]
    public static partial IntPtr GlobalFree(IntPtr memory);

    [LibraryImport(Kernel32)]
    public static partial nuint GlobalSize(IntPtr memory);

    [LibraryImport(Kernel32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool AttachConsole(uint processId);

    [LibraryImport(Kernel32)]
    public static partial int GetUserDefaultLocaleName(char* localeName, int size);

    [LibraryImport(Kernel32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GetUserPreferredUILanguages(uint flags, uint* count, char* buffer, uint* size);

    // ---- gdi32 --------------------------------------------------------------------------------

    [LibraryImport(Gdi32)]
    public static partial int SetDIBitsToDevice(IntPtr hdc, int xDest, int yDest, uint width, uint height,
        int xSrc, int ySrc, uint startScan, uint scanLines, void* bits, BITMAPINFOHEADER* info, uint usage);

    // ---- dwmapi -------------------------------------------------------------------------------

    [LibraryImport(Dwmapi)]
    public static partial int DwmSetWindowAttribute(IntPtr hwnd, uint attribute, void* value, uint size);

    // ---- imm32 --------------------------------------------------------------------------------

    [LibraryImport(Imm32)]
    public static partial IntPtr ImmGetContext(IntPtr hwnd);

    [LibraryImport(Imm32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ImmReleaseContext(IntPtr hwnd, IntPtr context);

    [LibraryImport(Imm32)]
    public static partial int ImmGetCompositionStringW(IntPtr context, uint index, void* buffer, uint bytes);

    [LibraryImport(Imm32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ImmSetCompositionWindow(IntPtr context, COMPOSITIONFORM* form);

    [LibraryImport(Imm32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ImmSetCandidateWindow(IntPtr context, CANDIDATEFORM* form);

    [LibraryImport(Imm32)]
    public static partial IntPtr ImmAssociateContext(IntPtr hwnd, IntPtr context);

    [LibraryImport(Imm32)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool ImmAssociateContextEx(IntPtr hwnd, IntPtr context, uint flags);

    // ---- shell32 ------------------------------------------------------------------------------

    [LibraryImport(Shell32, StringMarshalling = StringMarshalling.Utf16)]
    public static partial uint ExtractIconExW(string file, int index, IntPtr* large, IntPtr* small, uint count);

    // ---- Helpers ------------------------------------------------------------------------------

    public static int LoWord(nint value) => (short)(value & 0xFFFF);

    public static int HiWord(nint value) => (short)((value >> 16) & 0xFFFF);

    public static int LoWord(nuint value) => (ushort)(value & 0xFFFF);

    public static int HiWord(nuint value) => (short)((value >> 16) & 0xFFFF);

    /// <summary>A pointer message's client coordinates — SIGNED, because a captured drag reports
    /// positions left of and above the window as negatives, and a ushort read would put them at
    /// the far edge of a 65,535-pixel screen.</summary>
    public static (int X, int Y) PointOf(nint lParam) => (LoWord(lParam), HiWord(lParam));

    public static bool IsDown(int virtualKey) => (GetKeyState(virtualKey) & 0x8000) != 0;
}
