//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (the ResXFileCodeGenerator shape the IDE
//     writes beside Strings.resx). Manual changes will be lost on regeneration.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DefaultUIDashboard.Resources
{
    internal class Strings
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        internal Strings() { }

        internal static global::System.Resources.ResourceManager ResourceManager =>
            resourceMan ??= new global::System.Resources.ResourceManager(
                "DefaultUIDashboard.Resources.Strings", typeof(Strings).Assembly);

        internal static global::System.Globalization.CultureInfo? Culture { get; set; }

        internal static string Hero_Title
        {
            get { return ResourceManager.GetString("Hero.Title", Culture)!; }
        }

        internal static string Hero_Body
        {
            get { return ResourceManager.GetString("Hero.Body", Culture)!; }
        }

        internal static string Greeting
        {
            get { return ResourceManager.GetString("Greeting", Culture)!; }
        }
    }
}
