<Project>
    <Import Project="../../src/eQuantic.UI.Sdk/Sdk/Sdk.props" />

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Only UI library choice needs to be explicit -->
        <ProjectReference Include="..\..\src\eQuantic.UI.Tailwind\eQuantic.UI.Tailwind.csproj" />
        <ProjectReference Include="..\..\src\eQuantic.UI.Components\eQuantic.UI.Components.csproj" />
        <ProjectReference Include="..\..\src\eQuantic.UI.Lucide\eQuantic.UI.Lucide.csproj" />
        <ProjectReference Include="..\..\src\eQuantic.UI.Charts\eQuantic.UI.Charts.csproj" />
        <ProjectReference Include="..\..\src\eQuantic.UI.Charts.ChartJs\eQuantic.UI.Charts.ChartJs.csproj" />
        <ProjectReference Include="..\..\src\eQuantic.UI.Charts.ApexCharts\eQuantic.UI.Charts.ApexCharts.csproj" />
        <ProjectReference Include="..\..\src\eQuantic.UI.Lottie\eQuantic.UI.Lottie.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- Tailwind CSS plugins (installed automatically via embedded Bun) -->
        <BunPackage Include="tailwindcss-animate" Version="1.0.7" />
    </ItemGroup>

    <Import Project="../../src/eQuantic.UI.Sdk/Sdk/Sdk.targets" />

    <!-- Import Tailwind targets for CSS generation -->
    <Import Project="../../src/eQuantic.UI.Tailwind/Build/eQuantic.UI.Tailwind.targets" />
</Project>