using System.Globalization;
using System.Text;
using eQuantic.UI.Codegen;
using eQuantic.UI.Primitives;

namespace eQuantic.UI.Build;

/// <summary>
/// The app's <c>Assets/**/*.svg</c>, read once at BUILD time and written as one C# class of
/// <see cref="VectorDrawing"/> data.
/// <para>
/// This is what makes "point at a file" possible in a framework that runs in a browser: nothing at
/// runtime reads the file, on either target. The artwork becomes source, the source compiles into
/// the app, and the same bytes reach the DOM and the GPU.
/// </para>
/// <para>
/// A typed member per file rather than a path string, for the reason every generated surface in
/// this SDK exists: <c>Vectors.Mark</c> is a compile error when it is wrong, and
/// <c>Drawing("mark.svg")</c> is a blank space at runtime.
/// </para>
/// </summary>
public static class VectorCatalog
{
    /// <summary>
    /// Writes the catalog for every SVG under <paramref name="assetsDir"/>. Returns how many
    /// drawings it carried — zero writes nothing at all, so an app with no artwork gets no file
    /// and no empty class to wonder about.
    /// </summary>
    public static int Write(string assetsDir, string outputPath, string @namespace)
    {
        if (!Directory.Exists(assetsDir)) return 0;

        var files = Directory.GetFiles(assetsDir, "*.svg", SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.Ordinal)
            .ToList();
        if (files.Count == 0) return 0;

        var drawings = new List<(string Member, string Source, VectorDrawing Drawing)>();
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var file in files)
        {
            var drawing = SvgDocument.Parse(File.ReadAllText(file));
            // A file the subset cannot read is SKIPPED and said out loud: a member that draws
            // nothing would be a compile-time promise the screen does not keep.
            if (drawing.IsEmpty)
            {
                Console.Error.WriteLine(
                    $"eqicon: {Path.GetFileName(file)} has no shapes this subset can carry — skipped.");
                continue;
            }

            var member = MemberName(Path.GetRelativePath(assetsDir, file));
            // Two files that reduce to the same member name would generate the same property twice
            // and fail to compile far from the cause.
            if (!names.Add(member))
            {
                Console.Error.WriteLine(
                    $"eqicon: {Path.GetFileName(file)} would be a second '{member}' — skipped.");
                continue;
            }
            drawings.Add((member, Path.GetRelativePath(assetsDir, file).Replace('\\', '/'), drawing));
        }

        if (drawings.Count == 0) return 0;

        var code = new CodeWriter();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Written by eqicon from Assets/**/*.svg — do not edit by hand.");
        code.AppendLine("#nullable enable");
        // The catalog puts ITSELF in scope. A `<Using>` item in the SDK would have done it too, and
        // would have depended on this file existing before MSBuild evaluated the project — which on
        // a cold build it does not. A global using inside the file has no such ordering... and it
        // goes FIRST, because C# will not take one after an ordinary using.
        code.AppendLine($"global using {@namespace};");
        code.AppendLine("using eQuantic.UI.Primitives;");
        code.AppendLine();
        code.AppendLine($"namespace {@namespace};");
        code.AppendLine();
        code.AppendLine("/// <summary>The app's vector artwork, read from its <c>Assets</c> folder at build time.");
        code.AppendLine("/// Draw one with <c>Drawing(Vectors.Name, width)</c>.</summary>");
        using (code.BeginScope("public static class Vectors", "{", "}"))
        {
            foreach (var (member, source, drawing) in drawings)
            {
                code.AppendLine($"/// <summary><c>{source}</c> — {Number(drawing.Width)}×{Number(drawing.Height)}, "
                    + $"{drawing.Shapes.Count} shape{(drawing.Shapes.Count == 1 ? "" : "s")}.</summary>");
                code.AppendLine($"public static readonly VectorDrawing {member} = new VectorDrawing(");
                code.IndentLevel++;
                code.AppendLine($"{Number(drawing.MinX)}f, {Number(drawing.MinY)}f, "
                    + $"{Number(drawing.Width)}f, {Number(drawing.Height)}f, new VectorShape[]");
                using (code.BeginScope("{", "});"))
                {
                    foreach (var shape in drawing.Shapes) code.AppendLine(Shape(shape) + ",");
                }
                code.IndentLevel--;
                code.AppendLine();
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        var text = code.ToString();
        // Only when it CHANGED: rewriting the file every build re-triggers the compiler, and this
        // runs before every compile.
        if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != text)
            File.WriteAllText(outputPath, text);
        return drawings.Count;
    }

    private static string Shape(VectorShape shape)
    {
        var text = new StringBuilder("new VectorShape(");
        text.Append(Literal(shape.Path)).Append(", ").Append(Paint(shape.Fill));
        // Only as far as the defaults require — the emitted file is read by people diffing artwork.
        var needsStroke = shape.Stroke.Paints;
        var needsWidth = needsStroke || shape.StrokeWidth != 1;
        var needsRule = shape.EvenOdd;
        var needsOpacity = shape.Opacity != 1;
        if (needsStroke || needsWidth || needsRule || needsOpacity)
            text.Append(", ").Append(Paint(shape.Stroke));
        if (needsWidth || needsRule || needsOpacity)
            text.Append(", ").Append(Number(shape.StrokeWidth)).Append('f');
        if (needsRule || needsOpacity)
            text.Append(", ").Append(shape.EvenOdd ? "true" : "false");
        if (needsOpacity)
            text.Append(", ").Append(Number(shape.Opacity)).Append('f');
        return text.Append(')').ToString();
    }

    private static string Paint(VectorPaint paint) => paint.Kind switch
    {
        VectorPaintKind.Solid =>
            $"VectorPaint.Solid(Color.FromRgba({paint.Color.R}, {paint.Color.G}, {paint.Color.B}, {paint.Color.A}))",
        // An inherited paint carries only an alpha; full strength is the shared static.
        VectorPaintKind.Inherit when paint.Color.A == 255 => "VectorPaint.Inherit",
        VectorPaintKind.Inherit =>
            $"new VectorPaint(VectorPaintKind.Inherit, Color.FromRgba(0, 0, 0, {paint.Color.A}))",
        VectorPaintKind.LinearGradient or VectorPaintKind.RadialGradient when paint.Gradient is { } run =>
            $"VectorPaint.Gradients(VectorPaintKind.{paint.Kind}, {Gradient(run)})",
        _ => "VectorPaint.None",
    };

    /// <summary>
    /// A run of colours, written as the constructor a person could have typed. The stops are a
    /// collection expression rather than a helper: what an artwork's gradient IS belongs in the
    /// diff, so a designer changing a stop sees the colour change and not a call change.
    /// </summary>
    private static string Gradient(VectorGradient run)
    {
        var stops = string.Join(", ", run.Stops.Select(stop =>
            $"new VectorStop({Number(stop.Offset)}f, Color.FromRgba({stop.Color.R}, {stop.Color.G}, {stop.Color.B}, {stop.Color.A}))"));
        return $"new VectorGradient({Number(run.X1)}f, {Number(run.Y1)}f, {Number(run.X2)}f, "
            + $"{Number(run.Y2)}f, {Number(run.Radius)}f, {(run.UserSpace ? "true" : "false")}, [{stops}])";
    }

    /// <summary>
    /// A file path as a C# member: <c>brand/logo-dark.svg</c> → <c>BrandLogoDark</c>. Folders are
    /// part of the name rather than nested classes, because a folder in an assets tree is how a
    /// designer groups files, not a namespace the app agreed to.
    /// </summary>
    private static string MemberName(string relativePath)
    {
        var withoutExtension = relativePath[..^Path.GetExtension(relativePath).Length];
        var name = new StringBuilder();
        var capitalize = true;
        foreach (var c in withoutExtension)
        {
            if (c is '/' or '\\' or '-' or '_' or ' ' or '.')
            {
                capitalize = true;
                continue;
            }
            if (!char.IsLetterOrDigit(c)) continue;
            name.Append(capitalize ? char.ToUpperInvariant(c) : c);
            capitalize = false;
        }
        // A member cannot start with a digit, and `_2024Report` is what C# itself would need.
        if (name.Length == 0) return "Drawing";
        return char.IsDigit(name[0]) ? "_" + name : name.ToString();
    }

    private static string Literal(string value) => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Number(float value) => value.ToString("0.####", CultureInfo.InvariantCulture);
}
