using eQuantic.UI.Compiler.CodeGen;
using eQuantic.UI.Compiler.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace eQuantic.UI.Compiler.Services;

/// <summary>
/// A C# MEMBER MAY NOT TAKE A NAME THE RUNTIME'S COMPONENT ALREADY USES.
///
/// <para>
/// C# keeps three things apart that JavaScript folds into one key. A primary-constructor parameter
/// is a capture, a field is a field, an auto-property is a property, and the case differs from the
/// runtime's camelCase — but all three lower to <c>this.&lt;name&gt;</c>. So
/// <c>class StatTile(string label, bool centered = false)</c> assigned <c>this.centered</c>, which
/// SHADOWED the <c>centered()</c> the instance inherited, and the page failed only in the browser:
/// <c>AppUI.statTile(...).centered is not a function</c> (#245). The default is applied and
/// assigned even when the caller passes nothing, so not using the parameter does not help.
/// </para>
///
/// <para>
/// Shadowing a METHOD is a TypeError a reader can at least follow. Shadowing a FIELD was the worse
/// half — the assignment silently won, a value went missing, and the page rendered. That half is
/// gone from a COMPONENT rather than diagnosed: the runtime's component carried nine DOM properties
/// and fourteen handlers that a component never reads, and they moved down to
/// <see cref="!:HtmlElement"/> — as <c>declare</c>d types, which emit nothing and so leave the
/// prototype chain entirely. What this refuses is what is LEFT, and the
/// list is read from the runtime rather than written here (<c>Resources/runtime-members.txt</c>,
/// generated by <c>core/runtime-members.spec.ts</c> from the live prototype chain and pinned both
/// ways). A list typed by hand drifts the moment the runtime gains a method, and a guard that has
/// drifted is a guard that has stopped.
/// </para>
///
/// <para>
/// What is exempt is an <c>override</c>, not a method. A C# <c>Build</c> is meant to replace the
/// runtime's <c>build</c> — that is how a component is written — but a plain
/// <c>public void Mount() { }</c> overrides nothing and still emits <c>mount()</c> over the
/// runtime's <c>mount(container)</c>, so the component never mounts and nothing says why.
/// Measured: that is the emission, and the first version of this guard let it through while a
/// test of its own asserted it should.
/// </para>
/// </summary>
public static class ShadowedRuntimeMembers
{
    private const string ResourceName = "eQuantic.UI.Compiler.Resources.runtime-members.txt";

    private static readonly Dictionary<string, HashSet<string>> ByBase = Load();

    /// <summary>
    /// THROWS rather than returning nothing. An empty set is a guard that refuses everything it was
    /// written to refuse and says so to no one — every consumer would compile with no protection
    /// and find out in the browser, which is the exact failure this exists to prevent. The resource
    /// is embedded by the Compiler's own csproj, so its absence is a broken build of eqc rather than
    /// anything a consumer did, and it should read that way.
    /// </summary>
    private static Dictionary<string, HashSet<string>> Load()
    {
        using var stream = typeof(ShadowedRuntimeMembers).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"eqc is missing its embedded '{ResourceName}'. It is the list of members a component "
                + "already has, generated from the runtime by core/runtime-members.spec.ts and embedded "
                + "by eQuantic.UI.Compiler.csproj. Without it EQ2011 would refuse nothing and a member "
                + "shadowing the runtime's would fail only in the browser (#245).");
        using var reader = new StreamReader(stream);
        var byBase = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var line in reader.ReadToEnd()
                     .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var tab = line.IndexOf('\t');
            if (tab <= 0) continue;
            var baseName = line[..tab];
            if (!byBase.TryGetValue(baseName, out var members))
                byBase[baseName] = members = new HashSet<string>(StringComparer.Ordinal);
            members.Add(line[(tab + 1)..]);
        }
        return byBase.Count > 0
            ? byBase
            : throw new InvalidOperationException(
                $"eqc's embedded '{ResourceName}' names no base, which disables EQ2011 silently. "
                + "Regenerate it with EQ_UPDATE_RUNTIME_MEMBERS=1 on the runtime's vitest suite.");
    }

    /// <summary>
    /// The members the base this component ACTUALLY extends carries. One union of all of them would
    /// be simpler and wrong: the bases differ by eleven names — <c>setState</c>, <c>key</c>,
    /// <c>onMount</c>, <c>_sharedStateful</c> and the rest belong to a STATEFUL component — and a
    /// union refuses them on a stateless one, where they shadow nothing at all. <c>HtmlElement</c>
    /// is its own case again, carrying the DOM surface a component does not.
    /// <para>
    /// THE DECLARED NAME IS NOT THE ANSWER — the CHAIN is. An app's own base is ordinary
    /// (<c>class Child : MyStatelessBase</c>), and matching only the four fixture keys sent every
    /// one of them to the <c>Component</c> floor. Measured, that let this through with no
    /// diagnostic at all:
    /// <code>
    /// export class Child extends MyStatelessBase {
    ///     hydrate() {}
    ///     mount() {}
    /// }
    /// </code>
    /// Both replace the lifecycle <c>MyStatelessBase</c> inherited from <c>StatelessComponent</c>,
    /// and the component silently never mounts — the same failure EQ2011 exists to refuse, one
    /// class further down. So the model is ASKED: the base chain is walked to the first base the
    /// runtime declares, which resolves through any depth of app bases.
    /// </para>
    /// <para>
    /// A chain that ends in a base the model cannot see falls back to <c>Component</c>, and that is
    /// the INTERSECTION rather than a guess: an unseen base could be on either branch, and its
    /// three (<c>children</c>, <c>constructor</c>, <c>render</c>) are what both carry. Guessing
    /// <c>StatelessComponent</c> would refuse <c>mount</c> on an <c>HtmlElement</c> that never had
    /// it, which is the too-broad half of this same bug.
    /// </para>
    /// </summary>
    private static HashSet<string> MembersFor(ComponentDefinition component, SemanticModel? model)
    {
        if (component.BaseClassName is { Length: > 0 } declared && ByBase.TryGetValue(declared, out var exact))
            return exact;
        if (RuntimeBaseOf(component, model) is { } resolved && ByBase.TryGetValue(resolved, out var chained))
            return chained;
        return ByBase.TryGetValue("Component", out var floor) ? floor : [];
    }

    /// <summary>
    /// Walks up from this component to the first base the fixture names. Symbol-based on purpose:
    /// the chain is exactly what a name cannot answer, and the model resolves it even with no
    /// project compilation — a base the compiler has no reference for still arrives as an ERROR
    /// type carrying its name, which is all this needs. Answers null when the walk runs out.
    /// </summary>
    private static string? RuntimeBaseOf(ComponentDefinition component, SemanticModel? model)
    {
        if (model is null || component.SyntaxTree is null) return null;
        // The class the parser read, never the first of its name in the tree: two classes of one name
        // in two namespaces are two types, and the other one's chain is not this one's.
        TypeDeclarationSyntax? declaration = component.ClassSyntax ?? component.ValueTypeSyntax;
        if (declaration is null || model.SyntaxTree != component.SyntaxTree) return null;
        // `seen` guards a malformed cycle rather than a legal one: C# has no circular base, but a
        // half-written file is what a compiler runs on, and a walk that does not end is a hang.
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var current = (model.GetDeclaredSymbol(declaration) as INamedTypeSymbol)?.BaseType;
             current is not null && seen.Add(current.Name);
             current = current.BaseType)
        {
            if (ByBase.ContainsKey(current.Name)) return current.Name;
        }
        return null;
    }

    /// <summary>What each base carries — for a test that pins this against the runtime.</summary>
    public static IReadOnlyDictionary<string, IReadOnlyCollection<string>> All =>
        ByBase.ToDictionary(pair => pair.Key, pair => (IReadOnlyCollection<string>)pair.Value,
            StringComparer.Ordinal);

    /// <summary>
    /// Every member of <paramref name="component"/> that would land on a name the runtime uses —
    /// including the <c>_</c>-prefixed ones, which are the sharpest case rather than an exception.
    /// A leading underscore lowers UNCHANGED (<c>_count</c> → <c>this._count</c>) and is how state
    /// is written all over this repository, so <c>_mounted</c> or <c>_renderManager</c> is a field
    /// a component can reach by accident and the thing it corrupts is the lifecycle.
    /// </summary>
    public static List<CompilationError> Check(ComponentDefinition component, SemanticModel? model = null)
    {
        var errors = new List<CompilationError>();

        foreach (var parameter in component.Constructors
                     .Where(ctor => ctor.IsPrimaryConstructor)
                     .SelectMany(ctor => ctor.Parameters))
        {
            Collides(parameter.Name, "primary-constructor parameter");
        }

        foreach (var property in component.Properties.Where(p => !p.IsStatic))
            Collides(property.Name, "property");

        foreach (var field in component.ComponentFields.Where(f => !f.IsStatic))
            Collides(field.Name, "field");

        foreach (var method in component.Methods.Where(m => !m.IsStatic && !m.IsOverride))
            Collides(method.Name, "method");

        // A SERVER ACTION reaches the emission by a different door and so has to be checked by its
        // own name. `ParseMethods` skips it deliberately — its body runs on the server and
        // transpiling it would ship a DbContext to the browser — and the emitter then writes an RPC
        // stub from `ServerActions` instead. So the method is absent from the list above and present
        // in the output, which is the one combination that gets past a members-only check.
        // Measured: `[ServerAction] public async Task Mount()` on a stateful component emitted
        // `async mount() { return await getServerActionsClient().invoke('Panel/Mount', []) }` over
        // the runtime's `mount(container)`, with no diagnostic — the component never mounts, and
        // every render of it is a round trip to the server instead.
        foreach (var action in component.ServerActions)
            Collides(action.MethodName, "server action");

        return errors;

        void Collides(string name, string kind)
        {
            var lowered = name.ToCamelCase();
            if (!MembersFor(component, model).Contains(lowered)) return;
            // What the emission LOOKS like, which is the half a reader cannot see from the C#.
            var emitted = kind switch
            {
                "method" => $"{lowered}()",
                "server action" => $"async {lowered}()",
                _ => $"this.{lowered}",
            };
            errors.Add(new CompilationError
            {
                Code = "EQ2011",
                Message =
                    $"'{component.Name}.{name}' ({kind}) lowers to `{emitted}`, and a component "
                    + $"already has `{lowered}`. C# keeps a {kind} and a runtime member apart; "
                    + "JavaScript does not, so this would replace it and the page would fail only "
                    + $"in the browser. Rename it (`{Suggest(name)}`, say)."
                    + (kind == "method"
                        ? " An `override` is exempt: replacing a base member is what one is for."
                        : kind == "server action"
                            ? " The RPC stub the emitter writes for it lands on the same key, so the"
                              + " `[ServerAction]` attribute is no shelter."
                            : string.Empty),
                SourcePath = component.SourcePath ?? string.Empty,
            });
        }
    }

    /// <summary>A shape for the rename, not a promise: the runtime uses no `…Value` name, and
    /// pluralising `children` into `childrens` read worse than it helped.</summary>
    private static string Suggest(string name) => $"{name}Value";
}
