using eQuantic.UI.Compiler.CodeGen;
using eQuantic.UI.Compiler.Models;

namespace eQuantic.UI.Compiler.Services;

/// <summary>
/// A C# MEMBER MAY NOT TAKE A NAME THE RUNTIME'S COMPONENT ALREADY USES.
///
/// <para>
/// C# keeps three things apart that JavaScript folds into one key. A primary-constructor parameter
/// is a capture, a field is a field, an auto-property is a property, and the case differs from the
/// runtime's camelCase — but all three lower to <c>this.&lt;name&gt;</c>. So
/// <c>class StatTile(string label, bool centered = false)</c> assigned <c>this.centered</c>, which
/// SHADOWED the <c>centered()</c> the instance inherited, and the page failed only in the browser:
/// <c>AppUI.statTile(...).centered is not a function</c> (#245). The default is applied and
/// assigned even when the caller passes nothing, so not using the parameter does not help.
/// </para>
///
/// <para>
/// Shadowing a METHOD is a TypeError a reader can at least follow. Shadowing a FIELD was the worse
/// half — the assignment silently won, a value went missing, and the page rendered. That half is
/// gone rather than diagnosed: the runtime's component carried nine DOM fields and fourteen
/// handlers that nothing read, and they were deleted. What this refuses is what is LEFT, and the
/// list is read from the runtime rather than written here (<c>Resources/runtime-members.txt</c>,
/// generated by <c>core/runtime-members.spec.ts</c> from the live prototype chain and pinned both
/// ways). A list typed by hand drifts the moment the runtime gains a method, and a guard that has
/// drifted is a guard that has stopped.
/// </para>
///
/// <para>
/// What is exempt is an <c>override</c>, not a method. A C# <c>Build</c> is meant to replace the
/// runtime's <c>build</c> — that is how a component is written — but a plain
/// <c>public void Mount() { }</c> overrides nothing and still emits <c>mount()</c> over the
/// runtime's <c>mount(container)</c>, so the component never mounts and nothing says why.
/// Measured: that is the emission, and the first version of this guard let it through while a
/// test of its own asserted it should.
/// </para>
/// </summary>
public static class ShadowedRuntimeMembers
{
    private const string ResourceName = "eQuantic.UI.Compiler.Resources.runtime-members.txt";

    private static readonly HashSet<string> Names = Load();

    /// <summary>
    /// THROWS rather than returning nothing. An empty set is a guard that refuses everything it was
    /// written to refuse and says so to no one — every consumer would compile with no protection
    /// and find out in the browser, which is the exact failure this exists to prevent. The resource
    /// is embedded by the Compiler's own csproj, so its absence is a broken build of eqc rather than
    /// anything a consumer did, and it should read that way.
    /// </summary>
    private static HashSet<string> Load()
    {
        using var stream = typeof(ShadowedRuntimeMembers).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"eqc is missing its embedded '{ResourceName}'. It is the list of members a component "
                + "already has, generated from the runtime by core/runtime-members.spec.ts and embedded "
                + "by eQuantic.UI.Compiler.csproj. Without it EQ2011 would refuse nothing and a member "
                + "shadowing the runtime's would fail only in the browser (#245).");
        using var reader = new StreamReader(stream);
        var names = reader.ReadToEnd()
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToHashSet(StringComparer.Ordinal);
        return names.Count > 0
            ? names
            : throw new InvalidOperationException(
                $"eqc's embedded '{ResourceName}' is empty, which disables EQ2011 silently. "
                + "Regenerate it with EQ_UPDATE_RUNTIME_MEMBERS=1 on the runtime's vitest suite.");
    }

    /// <summary>The members a component already has — for a test that pins this against the runtime.</summary>
    public static IReadOnlyCollection<string> All => Names;

    /// <summary>
    /// Every member of <paramref name="component"/> that would land on a name the runtime uses —
    /// including the <c>_</c>-prefixed ones, which are the sharpest case rather than an exception.
    /// A leading underscore lowers UNCHANGED (<c>_count</c> → <c>this._count</c>) and is how state
    /// is written all over this repository, so <c>_mounted</c> or <c>_renderManager</c> is a field
    /// a component can reach by accident and the thing it corrupts is the lifecycle.
    /// </summary>
    public static List<CompilationError> Check(ComponentDefinition component)
    {
        var errors = new List<CompilationError>();

        foreach (var parameter in component.Constructors
                     .Where(ctor => ctor.IsPrimaryConstructor)
                     .SelectMany(ctor => ctor.Parameters))
        {
            Collides(parameter.Name, "primary-constructor parameter");
        }

        foreach (var property in component.Properties.Where(p => !p.IsStatic))
            Collides(property.Name, "property");

        foreach (var field in component.ComponentFields.Where(f => !f.IsStatic))
            Collides(field.Name, "field");

        foreach (var method in component.Methods.Where(m => !m.IsStatic && !m.IsOverride))
            Collides(method.Name, "method");

        return errors;

        void Collides(string name, string kind)
        {
            var lowered = name.ToCamelCase();
            if (!Names.Contains(lowered)) return;
            // What the emission LOOKS like, which is the half a reader cannot see from the C#.
            var emitted = kind == "method" ? $"{lowered}()" : $"this.{lowered}";
            errors.Add(new CompilationError
            {
                Code = "EQ2011",
                Message =
                    $"'{component.Name}.{name}' ({kind}) lowers to `{emitted}`, and a component "
                    + $"already has `{lowered}`. C# keeps a {kind} and a runtime member apart; "
                    + "JavaScript does not, so this would replace it and the page would fail only "
                    + $"in the browser. Rename it (`{Suggest(name)}`, say)."
                    + (kind == "method"
                        ? " An `override` is exempt: replacing a base member is what one is for."
                        : string.Empty),
                SourcePath = component.SourcePath ?? string.Empty,
            });
        }
    }

    /// <summary>A shape for the rename, not a promise: the runtime uses no `…Value` name, and
    /// pluralising `children` into `childrens` read worse than it helped.</summary>
    private static string Suggest(string name) => $"{name}Value";
}
