<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\eQuantic.UI.Core\eQuantic.UI.Core.csproj" />
        <ProjectReference Include="..\eQuantic.UI.Components\eQuantic.UI.Components.csproj" />
        <ProjectReference Include="..\eQuantic.UI.Server\eQuantic.UI.Server.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="**\*.cs" Exclude="obj\**;bin\**" PackagePath="tools\source\" />
    </ItemGroup>

</Project>
